// Bobot skor 1-5 untuk setiap opsi (index 0-4 = A-E) di setiap pertanyaan q1-q40
// 1 = vibe paling santai/pasrah/boncos, 5 = vibe paling produktif/ambis/cuan
// Bobot disusun mengikuti MAKNA tiap opsi (bukan acak), supaya skor benar-benar
// merepresentasikan pola jawaban orang, bukan ngumpul di tengah kalau dijawab acak.
// Dipakai untuk menghitung total skor (40-200) lalu dipetakan ke 30 golongan

export const BOBOT_SKOR = {
  // q1: Scroll TikTok(pasif) / tutorial(produktif kecil) / tiduran(pasif) / chat mantan ga dikirim(pasif) / bersih galeri(produktif kecil)
  q1: [1, 4, 1, 2, 3],
  // q2: musik keras(santai) / tahan napas(effort) / nunggu sepi(effort) / pasrah(santai) / cepat(efisien)
  q2: [2, 3, 3, 1, 5],
  // q3: scroll sosmed(pasif) / suara kipas(netral) / mikir masalalu(pasif) / cek kunci(waspada) / minum air(sehat)
  q3: [1, 2, 1, 3, 4],
  // q4: kuah banyak / nyemek / mentah / mewah(effort) / campur nasi -- netral semua, kasih variasi kecil
  q4: [2, 2, 1, 4, 3],
  // q5: kasih uang pas(baik) / pura2 ga liat(cuek) / nolak(cuek) / senyum terpaksa(netral) / kasih 2rb(minimal effort)
  q5: [5, 1, 1, 2, 3],
  // q6: barang kecil ilang -- random konyol, kasih variasi netral kecil
  q6: [2, 2, 3, 1, 2],
  // q7: flexing(impulsif) / resign(berani) / beli ga penting(impulsif) / diam(bijak) / sedekah(bijak+sosial)
  q7: [2, 4, 1, 3, 5],
  // q8: 1 jam(parah) / nunggu mood(parah) / tidur sebentar(parah) / nunggu diingetin(parah) / ga berangkat(paling parah)
  q8: [2, 2, 2, 2, 1],
  // q9: stalking mantan(unproduktif) / belanja(impulsif) / bersih galeri(produktif kecil) / nonton tutorial(produktif kecil) / tidur(pasif)
  q9: [1, 1, 3, 4, 1],
  // q10: makin sering ngomong sendiri makin "unik", tapi ga nyambung produktivitas -- netral, variasi kecil
  q10: [2, 3, 2, 3, 4],
  // q11: app boros baterai -- netral, gak berkorelasi ke skor, kasih semua sama
  q11: [3, 3, 3, 3, 3],
  // q12: nasi uduk/bubur(isi) / roti(simpel) / air putih(ekstrim hemat) / nggak sarapan(ekstrim hemat negatif)
  q12: [3, 3, 4, 2, 1],
  // q13: batalin(pasif) / tetap pergi(niat) / nunggu reda(pasif) / poncho(siap) / terobos(niat)
  q13: [1, 4, 2, 4, 5],
  // q14: tiap hari ngomong diet(banyak omong) / abis makan(reaktif) / awal bulan(rutin) / ga pernah(realistis) / diajak doang(pasif)
  q14: [1, 2, 3, 5, 2],
  // q15: fast response(produktif) / slow(netral) / kalo ingat(pasif) / read doang(pasif) / ga dibalas(paling pasif)
  q15: [5, 3, 2, 2, 1],
  // q16: langsung read(produktif) / mute selamanya(menghindar) / nanti malam(nunda) / lock screen(setengah niat) / diabaikan(pasif)
  q16: [5, 1, 2, 3, 1],
  // q17: HP/dompet/powerbank netral, semua di atas(siap) / cuma badan(santai ekstrim)
  q17: [3, 3, 3, 4, 1],
  // q18: hal bikin emosi -- netral semua
  q18: [3, 3, 3, 3, 3],
  // q19: uang banyak sendirian(ambis) / teman banyak bokek(sosial-boncos) / pacar pelit(netral) / santai ga tujuan(pasif) / sibuk kaya(ambis)
  q19: [4, 1, 2, 1, 5],
  // q20: cek layar(cuek diri) / cek orang(sosial) / pura2(menghindar) / istighfar(reflektif) / panik ambil(reaktif)
  q20: [2, 4, 1, 3, 3],
  // q21: cuan(tinggi) / boncos self-reward(impulsif rendah) / gajian jauh(rendah) / numpang ortu(rendah) / aman pas2an(menengah)
  q21: [5, 1, 2, 1, 3],
  // q22: checkout shopee(impulsif) / kopi(kecil) / topup game(impulsif) / admin transfer(ga terhindarkan) / camilan(kecil)
  q22: [1, 3, 1, 4, 3],
  // q23: gaji pokok(stabil) / side hustle(produktif tinggi) / dana ortu(rendah) / giveaway(untung2an) / warisan(pasif)
  q23: [4, 5, 1, 2, 2],
  // q24: hp ram besar(konsumtif) / skincare(konsumtif) / kendaraan nyicil(beban) / harapan&mimpi(non-material) / foto kenangan(non-material)
  q24: [2, 2, 2, 3, 3],
  // q25: saham/kripto(tinggi) / skincare(rendah) / makanan(rendah) / nabung bantal(rendah-aman) / ilmu/kursus(tinggi produktif)
  q25: [5, 1, 1, 2, 5],
  // q26: beli kuota(kebutuhan) / makan enak(konsumtif) / ditabung(hemat) / jaga2(hemat) / tarik semua(impulsif)
  q26: [3, 2, 4, 4, 1],
  // q27: sultan tanpa kerja(halu) / stay home affiliate(produktif) / bos besar(ambis tinggi) / tenang sederhana(stabil) / traveling(konsumtif)
  q27: [1, 4, 5, 3, 2],
  // q28: pura2 sibuk(menghindar) / uninstall app belanja(disiplin) / jual barang(proaktif) / puasa(disiplin) / minjem teman(rendah)
  q28: [1, 4, 5, 3, 1],
  // q29: tiket konser(hiburan mahal) / skincare(konsumtif) / paket data(kebutuhan) / flash sale(impulsif) / bensin(kebutuhan)
  q29: [2, 2, 4, 1, 4],
  // q30: jadi OKB(ambis tinggi) / beli barang impian(konsumtif) / lunas cicilan(disiplin) / hidup tenang(stabil) / kasih ortu(sosial-tinggi)
  q30: [5, 2, 4, 3, 5],
  // q31: karyawan(stabil) / affiliate(produktif-variatif) / trader(ambis tinggi) / freelancer(variatif) / pelajar(belum produktif)
  q31: [3, 4, 5, 3, 1],
  // q32: di bawah UMR(rendah) / setara UMR(menengah) / di atas UMR(tinggi) / sultan ga menentu(variatif tinggi) / ga ada pendapatan(rendah)
  q32: [2, 3, 4, 5, 1],
  // q33: hemat<1jt(disiplin) / normal(stabil) / hedon(konsumtif) / highclass(konsumtif tinggi) / ga pernah ngitung(impulsif)
  q33: [4, 3, 2, 1, 1],
  // q34: belum punya emas(rendah) / 1-5gr(mulai) / 5-20gr(menengah) / >20gr(tinggi) / palsu doang(rendah-receh)
  q34: [1, 2, 3, 5, 1],
  // q35: masih chat mantan(belum move on) / blok total(tegas) / diem2an(ambigu) / jadi temen(dewasa) / ga punya mantan(netral)
  q35: [2, 4, 2, 5, 3],
  // q36: belum pernah pindah(stabil) / 1x(wajar) / 2-3x(aktif cari) / >3x(sangat aktif/gelisah) / di tempat pertama(stabil)
  q36: [3, 3, 4, 5, 3],
  // q37: gak ada utang(aman) / ada kecil(masih aman) / ada lumayan(waspada) / banyak(parah) / nyicil terus(parah)
  q37: [5, 4, 2, 1, 1],
  // q38: gak ada yang tau(privat) / pasangan(privat-wajar) / keluarga(wajar) / semua temen(terbuka) / flex semua(impulsif sosial)
  q38: [3, 4, 3, 2, 1],
  // q39: ditabung semua(disiplin) / bayar utang(bijak) / healing(konsumtif) / belanja impian(konsumtif) / dibagi keluarga(sosial-tinggi)
  q39: [5, 5, 2, 1, 4],
  // q40: staycation(konsumtif sedang) / mudik(sosial-keluarga) / healing sendiri(self-care) / kerja sampingan(produktif tinggi) / tidur doang(pasif)
  q40: [3, 3, 2, 5, 1],
};

// 30 golongan, diurutkan dari skor rendah ke tinggi
// Setiap golongan punya 20 variasi deskripsi, dipilih acak saat ditampilkan
export const GOLONGAN = [
  {
    nama: "Golongan Rebahan Mutlak",
    deskripsi: [
      "Energi hidupmu 90% dihabiskan di kasur, dan itu sudah final.",
      "Kasur adalah kantor, ruang meeting, dan tempat healing sekaligus.",
      "Gravitasi kasur lebih kuat dari niat bangun pagi.",
      "Rebahan bukan istirahat buatmu, itu gaya hidup permanen.",
      "Kalau rebahan jadi cabang olahraga, kamu atlet nasional.",
      "Mager bukan kelemahan, itu identitas yang kamu rawat dengan setia.",
      "Selimut adalah zona nyaman paling sah di hidupmu.",
      "Bangun dari kasur butuh effort sebesar bangun negara.",
      "Posisi favoritmu cuma satu: horizontal, sepanjang hari.",
      "Hidup kamu punya satu prinsip: kalau bisa rebahan, kenapa duduk.",
      "Kasurmu kenal kamu lebih baik dari siapapun di hidupmu.",
      "Kamu udah expert level dalam seni menunda hari.",
      "Rebahan itu bukan pilihan, itu panggilan jiwa.",
      "Kalau ada penghargaan rebahan terlama, kamu juaranya.",
      "Energi terbesar dalam hidupmu dipakai buat mindahin posisi tidur.",
      "Setiap rencana besar berakhir di kasur dengan posisi miring.",
      "Niat produktif selalu kalah lawan empuknya bantal.",
      "Kamu dan kasur itu satu paket yang gak terpisahkan.",
      "Mager level dewa, sampai napas aja rasanya males.",
      "Kasur bukan tempat tidur, itu basecamp permanen hidupmu.",
    ],
  },
  {
    nama: "Golongan Pasrah Sejati",
    deskripsi: [
      "Hidup mengalir aja, gak ada yang perlu dipaksain.",
      "Apapun yang terjadi, terjadilah. Itu motto hidupmu.",
      "Kamu udah damai sama hidup yang gak selalu sesuai rencana.",
      "Pasrah bukan nyerah, itu cara kamu bertahan dengan tenang.",
      "Rencana boleh ada, tapi kamu gak pernah maksa hasil.",
      "Kamu lebih milih ngalir kayak air daripada lawan arus.",
      "Stress itu pilihan, dan kamu pilih untuk gak stress.",
      "Apapun hasilnya, kamu udah siap terima dengan lapang dada.",
      "Hidup ini drama, dan kamu cuma penonton yang santai.",
      "Kamu jalanin hidup kayak nonton series, nikmatin tiap episodenya.",
      "Gak ada yang bisa goyangin ketenangan batinmu.",
      "Kamu percaya semua ada waktunya, gak perlu buru-buru.",
      "Yang penting jalanin aja, hasil biar semesta yang atur.",
      "Kamu jenis orang yang bilang 'gapapa' di segala situasi.",
      "Overthinking bukan kosakata yang ada di kamusmu.",
      "Kamu udah lulus sekolah kehidupan: terima apa adanya.",
      "Drama orang lain numpuk, kamu tetap kalem aja.",
      "Kamu pilih damai daripada ribut soal hal yang gak penting.",
      "Buat kamu, kekhawatiran itu cuma buang-buang energi.",
      "Ketenanganmu udah level biksu, gak gampang terpancing.",
    ],
  },
  {
    nama: "Golongan Boncos Kronis",
    deskripsi: [
      "Tanggal muda sultan, tanggal tua jadi rakyat biasa lagi.",
      "Dompetmu punya siklus bulanan yang lebih teratur dari kalender.",
      "Gajian itu cuma numpang lewat sebentar di rekeningmu.",
      "Self-reward udah jadi kebiasaan yang sulit dihentikan.",
      "Awal bulan flexing, akhir bulan minta tolong temen.",
      "Boncosmu bukan kebetulan, itu hasil kerja keras belanja.",
      "Saldo rekeningmu turun lebih cepat dari mood orang PMS.",
      "Kamu jenis orang yang belanja dulu, mikir belakangan.",
      "Diskon itu undangan resmi buatmu buat checkout semua keranjang.",
      "Tanggal tua adalah ujian keimanan finansial terberat.",
      "Self-reward kamu sebanyak alasan kamu buat self-reward.",
      "Dompetmu lebih sering kosong daripada penuhnya.",
      "Tanggal gajian dan tanggal boncos jaraknya cuma seminggu.",
      "Kamu hidup dari gajian ke gajian dengan penuh drama.",
      "Belanja itu terapi, walau efeknya cuma sehari dua hari.",
      "Kamu ahli bikin alasan kenapa belanja itu 'kebutuhan'.",
      "Akhir bulan adalah waktu refleksi soal keputusan belanja.",
      "Cicilan dan keinginan selalu menang lawan logika menabung.",
      "Tabungan cuma konsep, prakteknya susah banget.",
      "Kamu udah hafal banget rasanya tanggal tua yang menyiksa.",
    ],
  },
  {
    nama: "Golongan Numpang Hidup",
    deskripsi: [
      "Disubsidi keluarga itu bukan aib, itu strategi.",
      "Kamu jenis orang yang masih setia sama subsidi orang tua.",
      "Hidup nyaman karena ada yang nanggung di belakang.",
      "Kamu udah jago banget manfaatin privilege keluarga.",
      "Bukan males cari uang, cuma belum nemu motivasi yang pas.",
      "Hidupmu masih bergantung sama dompet orang tua.",
      "Kamu tau cara survive tanpa harus capek-capek kerja.",
      "Rezekimu masih nebeng di rezeki orang lain dulu.",
      "Belum mandiri secara finansial, tapi santai aja jalaninnya.",
      "Kamu masih di fase belajar hidup, jadi numpang itu wajar.",
      "Subsidi keluarga bikin hidupmu jauh lebih ringan.",
      "Kamu tipe yang percaya rezeki keluarga juga rezekimu.",
      "Belum kerja bukan masalah selama masih ada yang support.",
      "Kamu santai aja walau belum punya pemasukan sendiri.",
      "Hidup dari kemurahan hati orang lain itu skill tersendiri.",
      "Kamu paham banget cara hemat energi: biar orang lain usaha.",
      "Comfort zone kamu dijaga ketat sama support system keluarga.",
      "Belum punya penghasilan tapi gaya hidup tetap jalan.",
      "Kamu hidup di bawah payung perlindungan finansial keluarga.",
      "Belum saatnya mandiri, masih nikmatin masa numpang.",
    ],
  },
  {
    nama: "Golongan PHP Sepanjang Masa",
    deskripsi: [
      "Niatnya banyak, eksekusinya nanti dulu.",
      "Kamu jago bikin rencana, tapi realisasinya sering ngilang.",
      "Janji ke diri sendiri lebih sering diingkari dari janji ke orang.",
      "Semua rencana keren ada di kepala, belum ada di kenyataan.",
      "Kamu ahli ngomong 'besok mulai' selama bertahun-tahun.",
      "To-do list-mu panjang, yang dicentang cuma sedikit.",
      "Niat baik kamu banyak banget, tapi tetap jadi wacana.",
      "Kamu spesialis dalam memberi harapan ke diri sendiri.",
      "Mood adalah penentu utama apakah rencana berjalan atau tidak.",
      "Kamu sering bilang 'iya nanti' dan beneran nanti banget.",
      "Resolusi tahun baru kamu paling rajin dibuat, paling males dijalanin.",
      "Antara niat dan aksi ada jarak yang luas banget.",
      "Kamu jago banget kasih harapan palsu ke diri sendiri.",
      "Rencana besar selalu kalah sama rasa males yang dadakan.",
      "Kamu tau caranya memotivasi diri, tapi gak tau caranya gerak.",
      "Setiap deadline jadi pengingat kalau kamu PHP lagi.",
      "Kamu produktif di kepala, pasif di kenyataan.",
      "Niat udah 100%, eksekusi baru nyampe 10%.",
      "Kamu pakar dalam menunda hal-hal penting tanpa rasa bersalah.",
      "Wacana kamu lebih banyak dari pencapaian yang udah jadi.",
    ],
  },
  {
    nama: "Golongan Mager Akut",
    deskripsi: [
      "Kalau mager ada medalinya, kamu juara umum.",
      "Gerak sedikit aja udah berasa olahraga berat.",
      "Maleslah jadi alasan paling masuk akal buat segala hal.",
      "Mager kamu udah level kronis, gak ada obatnya.",
      "Setiap aktivitas dipertimbangkan: worth it gak buat gerak.",
      "Remote dan delivery online adalah penyelamat hidupmu.",
      "Kamu jago banget cari cara biar gak perlu beranjak dari tempat.",
      "Mager bukan fase, itu kepribadian.",
      "Kamu lebih nyaman diem di tempat daripada eksplor sesuatu.",
      "Setiap rencana keluar rumah selalu kalah sama rasa mager.",
      "Kamu ahli banget bikin alasan buat gak ngapa-ngapain.",
      "Gerak badan itu opsional, mager itu wajib.",
      "Kamu spesialis rebahan sambil scroll tanpa tujuan jelas.",
      "Effort minimal, hasil dipikirin nanti aja.",
      "Mager udah jadi gaya hidup yang kamu syukuri.",
      "Kamu paham banget seni bertahan tanpa banyak gerak.",
      "Setiap undangan keluar rumah dipikir dua ratus kali.",
      "Kamu juara dunia dalam kategori 'gak mau ribet'.",
      "Energimu lebih sering dipakai buat mikir daripada gerak.",
      "Mager itu nyaman, dan kamu nikmatin banget kenyamanannya.",
    ],
  },
  {
    nama: "Golongan Receh Bahagia",
    deskripsi: [
      "Hidup sederhana, bahagia tetap maksimal.",
      "Kebahagiaanmu gak butuh budget besar, cukup hal-hal kecil.",
      "Kamu nemu kebahagiaan di tempat yang orang lain anggap biasa.",
      "Hidup pas-pasan tapi hati selalu kaya rasa syukur.",
      "Kamu jago bikin hal kecil jadi momen yang berkesan.",
      "Gak butuh mewah buat seneng, yang penting hati tenang.",
      "Senyummu murah tapi tulus, gak butuh validasi mahal.",
      "Kebahagiaan receh adalah filosofi hidup yang kamu pegang.",
      "Kamu paham kebahagiaan gak diukur dari isi dompet.",
      "Hal sederhana udah cukup bikin harimu terasa lengkap.",
      "Kamu nikmatin hidup tanpa perlu banding-bandingin sama orang.",
      "Sukacita kecil tiap hari lebih berarti dari kemewahan sesaat.",
      "Kamu jenis orang yang bisa bahagia walau cuma modal seadanya.",
      "Hidupmu sederhana, tapi rasa puasnya gak kalah dari yang mewah.",
      "Kamu tau caranya menghargai hal kecil yang sering dilewatkan orang.",
      "Walau pas-pasan, kamu tetap bisa ketawa lepas tiap hari.",
      "Receh tapi konsisten, itu kebahagiaan versimu.",
      "Kamu gak butuh banyak buat ngerasa cukup.",
      "Kesederhanaanmu justru jadi sumber ketenangan yang asli.",
      "Bahagia versi kamu itu simpel, tapi tetap penuh makna.",
    ],
  },
  {
    nama: "Golongan Halu Produktif",
    deskripsi: [
      "Mimpi besar, progress nyicil, tapi tetap jalan.",
      "Kamu suka berkhayal tinggi, tapi diem-diem usaha juga jalan.",
      "Halu kamu bukan kosong, ada progress kecil di baliknya.",
      "Mimpi setinggi langit, tapi kamu tetap bangun pondasi pelan-pelan.",
      "Imajinasimu liar, tapi langkahmu tetap nyata walau kecil.",
      "Kamu tau caranya mimpi besar tanpa lupa kerja kecil tiap hari.",
      "Visi kamu jauh ke depan, eksekusinya dicicil dikit-dikit.",
      "Halu boleh, tapi kamu tetap nyiapin fondasi buat wujudin itu.",
      "Kamu percaya mimpi gede butuh proses, bukan instan.",
      "Khayalan kamu produktif, bukan cuma sekedar lamunan kosong.",
      "Setiap mimpi besar kamu, ada usaha kecil yang nyertain.",
      "Kamu jenis orang yang mimpi tinggi tapi tetap kerja keras pelan.",
      "Imajinasi kamu jadi bahan bakar buat usaha yang konsisten.",
      "Kamu gak cuma ngomong, ada langkah nyata walau dikit-dikit.",
      "Mimpi besar gak bikin kamu lupa step kecil yang harus dijalani.",
      "Kamu tau mimpi tanpa aksi cuma jadi angan, makanya tetap gerak.",
      "Khayalanmu jadi motivasi buat usaha yang nyata, bukan cuma fantasi.",
      "Visi besar, kerja nyata, walau hasilnya butuh waktu.",
      "Kamu percaya proses kecil bisa nyampe ke mimpi besar.",
      "Halu kamu terarah, ada usaha yang nyertain tiap langkahnya.",
    ],
  },
  {
    nama: "Golongan Santuy Berkelas",
    deskripsi: [
      "Santai tapi tetap kelihatan punya rencana.",
      "Kamu relax tapi tetap punya arah yang jelas.",
      "Gaya hidupmu kalem, tapi semua tetap terkontrol.",
      "Kamu santai menjalani hidup tanpa kehilangan fokus.",
      "Walau gak terburu-buru, kamu tetap tau tujuan akhirmu.",
      "Ketenanganmu bukan berarti gak punya ambisi.",
      "Kamu kelihatan santai, tapi sebenarnya semua udah dipikirkan.",
      "Gaya hidupmu effortless, tapi hasilnya tetap rapi.",
      "Kamu jenis orang yang chill tapi tetap on track.",
      "Santaimu itu kelas, bukan asal males-malesan.",
      "Kamu tau cara nikmatin proses tanpa kehilangan progres.",
      "Hidupmu kalem, tapi rencana tetap berjalan di belakang.",
      "Kamu gak panik, tapi tetap produktif dengan caramu sendiri.",
      "Gaya santaimu justru bikin orang lain salah sangka kamu gak serius.",
      "Kamu bisa rileks sambil tetap mengejar target.",
      "Ketenangan adalah strategi, bukan kemalasan.",
      "Kamu jalanin hidup dengan tempo sendiri, tapi tetap maju.",
      "Santaimu terukur, gak asal-asalan.",
      "Kamu tau kapan harus rileks dan kapan harus gerak.",
      "Vibe kamu kalem, tapi hasil kerjamu tetap kelihatan.",
    ],
  },
  {
    nama: "Golongan Cukup-Cukup Aja",
    deskripsi: [
      "Gak kekurangan, gak juga kelebihan. Pas.",
      "Hidupmu seimbang, gak ada drama berlebihan.",
      "Kamu jenis orang yang puas dengan apa yang udah ada.",
      "Semua serba cukup, gak kurang gak lebih.",
      "Kamu gak ngoyo, tapi juga gak ketinggalan.",
      "Hidupmu stabil, gak naik drastis gak turun parah.",
      "Kamu tau cara menikmati hidup yang pas-pas aja.",
      "Standar hidup kamu realistis, gak muluk-muluk.",
      "Kamu nyaman dengan ritme hidup yang biasa-biasa aja.",
      "Semuanya cukup, dan itu bikin kamu tenang.",
      "Kamu gak butuh lebih, yang ada sekarang udah pas.",
      "Hidup sederhana tapi gak kekurangan, itu kamu.",
      "Kamu menghindari ekstrem, pilih jalan tengah yang aman.",
      "Cukup itu kata kunci hidupmu, gak perlu lebih dari itu.",
      "Kamu puas dengan pencapaian yang sewajarnya.",
      "Gak ambisius berlebihan, tapi juga gak diam aja.",
      "Kamu tau batas kemampuan dan menerimanya dengan baik.",
      "Hidupmu jauh dari drama finansial maupun emosional.",
      "Kamu pilih stabilitas dibanding ambisi yang berisiko.",
      "Semua serba pas buatmu, dan itu yang membuatmu tenang.",
    ],
  },
  {
    nama: "Golongan Hemat Pangkal Survive",
    deskripsi: [
      "Bukan pelit, cuma realistis sama dompet.",
      "Kamu tau caranya bertahan dengan pengeluaran minim.",
      "Hemat itu bukan pilihan, itu kebutuhan buatmu.",
      "Kamu jago banget mengatur uang biar cukup sampai akhir bulan.",
      "Setiap rupiah dihitung dengan teliti biar gak boncos.",
      "Kamu paham banget cara survive dengan budget terbatas.",
      "Prioritasmu jelas: kebutuhan dulu, keinginan belakangan.",
      "Kamu spesialis cari diskon dan promo demi efisiensi.",
      "Hidup hemat bukan beban, itu strategi survival kamu.",
      "Kamu tau gimana caranya hidup cukup tanpa boros.",
      "Disiplin finansial kamu cukup kuat buat ukuran rata-rata orang.",
      "Setiap pengeluaran dipikir matang sebelum dieksekusi.",
      "Kamu realistis soal kemampuan dan gak maksa gaya hidup.",
      "Hemat kamu bukan karena pelit, tapi karena sadar diri.",
      "Kamu tau prioritas dan gak gampang tergoda belanja impulsif.",
      "Kebiasaan hematmu udah jadi insting, bukan paksaan.",
      "Kamu paham banget arti kata 'cukup' dalam hidup sehari-hari.",
      "Survival mode adalah mode default hidupmu.",
      "Kamu rajin mikir dua kali sebelum keluarin uang.",
      "Hemat pangkal aman, itu prinsip yang kamu pegang erat.",
    ],
  },
  {
    nama: "Golongan Sibuk Tapi Bingung",
    deskripsi: [
      "Banyak kerjaan, tapi arah hidup masih dicari.",
      "Kamu sibuk terus, tapi sering nanya 'ini buat apa sih?'",
      "Schedule penuh, tapi tujuan akhirnya masih kabur.",
      "Kamu kerja keras, tapi belum tau ke mana arahnya.",
      "Setiap hari sibuk, tapi progress kelihatannya jalan di tempat.",
      "Kamu jago multitasking, tapi sering kehilangan fokus utama.",
      "Banyak yang dikerjain, tapi belum jelas mana yang prioritas.",
      "Kamu capek karena sibuk, tapi belum capek karena hasil.",
      "Hidupmu penuh aktivitas, tapi makna di baliknya masih dicari.",
      "Kamu ngerasa produktif, tapi sering bingung produktif buat apa.",
      "Energi kamu kepake banyak, hasilnya kadang gak sebanding.",
      "Kamu sibuk ngejar banyak hal sekaligus tanpa fokus jelas.",
      "Rutinitas padat, tapi pertanyaan 'ini bener gak sih' tetap muncul.",
      "Kamu gercep kerja, tapi arah jangka panjangnya masih nyari.",
      "Banyak proyek jalan, tapi belum ada yang beres total.",
      "Kamu kelihatan sibuk dari luar, tapi dalemnya masih bingung.",
      "Waktu habis buat kerja, tapi visi besar belum kebentuk jelas.",
      "Kamu jalan terus walau kadang gak yakin ke arah mana.",
      "Sibuk itu pasti, tapi makna sibuknya masih dicari-cari.",
      "Kamu produktif secara waktu, belum produktif secara arah.",
    ],
  },
  {
    nama: "Golongan Ambis Setengah Hati",
    deskripsi: [
      "Niat ambis ada, eksekusi kadang nyerah duluan.",
      "Kamu start dengan semangat, tapi sering berhenti di tengah jalan.",
      "Motivasi tinggi di awal, konsistensi yang jadi masalah.",
      "Kamu punya target besar, tapi gampang goyah pas capek dikit.",
      "Niat ambis kamu nyala, tapi gampang padam kalau ketemu hambatan.",
      "Semangat 45 di awal, tapi semangat 5 di pertengahan.",
      "Kamu suka mulai banyak hal, tapi jarang nyelesain semuanya.",
      "Ambisi kamu real, tapi daya tahannya masih perlu dilatih.",
      "Kamu jago bikin target, tapi sering revisi target jadi lebih santai.",
      "Niatnya serius, tapi distraksi gampang banget bikin kamu belok.",
      "Kamu punya potensi besar, tapi konsistensi masih jadi tantangan.",
      "Setengah jalan kamu udah ngerasa cukup, padahal belum tuntas.",
      "Kamu ambis di kepala, tapi praktiknya naik turun.",
      "Energi awal kamu kuat, tapi staminanya perlu di-charge ulang.",
      "Kamu suka challenge diri sendiri, tapi sering nyerah di tengah.",
      "Target tinggi kamu pasang, realisasinya kadang setengah-setengah.",
      "Kamu punya potensi ambis penuh, tinggal nambah konsistensi.",
      "Niat kerja keras kamu jujur, cuma kadang kalah sama rasa males.",
      "Kamu tau caranya mulai, tapi masih belajar caranya bertahan.",
      "Ambisimu jujur dan real, cuma butuh sedikit lebih gigih.",
    ],
  },
  {
    nama: "Golongan Stabil Kalem",
    deskripsi: [
      "Gak heboh, tapi semua berjalan terkendali.",
      "Kamu kalem di luar, tapi dalemnya tetap on point.",
      "Hidupmu stabil, gak ada drama yang gak perlu.",
      "Kamu jalanin segalanya dengan tenang dan terukur.",
      "Tanpa banyak gerak, tapi hasilnya tetap konsisten.",
      "Kamu jenis orang yang gak gampang panik dalam situasi apapun.",
      "Stabilitas adalah kekuatanmu, bukan kelemahan.",
      "Kamu jarang ribut, tapi semua urusan tetap kelar.",
      "Ketenanganmu bikin orang sekitar juga ikut tenang.",
      "Kamu gak butuh drama buat ngerasa hidup punya progres.",
      "Vibe kalem kamu menyembunyikan kerja keras yang konsisten.",
      "Kamu tau caranya tetap produktif tanpa harus terlihat sibuk banget.",
      "Hidupmu terkendali, gak ada yang lepas dari radar.",
      "Kamu jalan pelan tapi pasti, gak suka buru-buru.",
      "Ketenangan kamu adalah hasil dari kebiasaan yang konsisten.",
      "Kamu gak suka heboh, tapi semua tugas tetap terselesaikan.",
      "Energi kamu stabil, gak naik turun drastis.",
      "Kamu kelihatan santai, tapi semua di bawah kontrol penuh.",
      "Hidupmu seimbang antara kerja dan ketenangan batin.",
      "Kamu jenis orang yang reliable tanpa harus banyak bicara.",
    ],
  },
  {
    nama: "Golongan Produktif Kepo",
    deskripsi: [
      "Kerja jalan, kepoin orang lain juga jalan.",
      "Kamu multitasking antara kerjaan dan urusan orang lain.",
      "Produktif tapi tetap update sama gosip terbaru.",
      "Kamu bisa kerja serius sambil tetap kepo sama sekitar.",
      "Fokus kerja kamu tinggi, fokus kepo juga gak kalah tinggi.",
      "Kamu jago bagi waktu antara deadline dan drama orang lain.",
      "Produktivitas kamu jalan barengan sama rasa penasaran yang besar.",
      "Kamu tipe yang kerja cepat, tapi tetap update timeline orang.",
      "Selesai kerja, langsung lanjut kepoin kehidupan orang lain.",
      "Kamu kombinasi sempurna antara pekerja keras dan si paling update.",
      "Energi kamu terbagi rata antara produktivitas dan rasa kepo.",
      "Kamu bisa serius kerja, tapi tetap gak ketinggalan info terbaru.",
      "Multitasking kamu unik: kerjaan kelar, kepo juga kelar.",
      "Kamu jenis orang yang produktif tapi tetap update sosial.",
      "Sambil ngerjain tugas, kamu tetap mantau circle pertemanan.",
      "Kamu bisa fokus kerja tanpa harus melewatkan info penting orang lain.",
      "Produktivitasmu gak bikin kamu ketinggalan berita sekitar.",
      "Kamu jago nyambi antara nyelesain kerjaan dan stalking timeline.",
      "Kerja keras dan kepo jalan bareng dalam hidupmu.",
      "Kamu bisa serius produktif, tapi tetap update sama lingkungan.",
    ],
  },
  {
    nama: "Golongan Hustler Receh",
    deskripsi: [
      "Usaha jalan terus walau hasilnya masih cuan kecil.",
      "Kamu gak nyerah walau cuannya belum besar-besar.",
      "Effort kamu maksimal, walau hasilnya masih bertahap.",
      "Kamu rajin usaha sambil sabar nunggu hasil yang lebih besar.",
      "Cuan kecil tetap kamu syukuri sambil terus berusaha.",
      "Kamu konsisten kerja keras meski belum nyampe target besar.",
      "Setiap rupiah hasil kerja keras kamu hargai dengan baik.",
      "Kamu gak gede-gedean, tapi tetap konsisten cari peluang.",
      "Usaha kecil kamu jalanin dengan serius dan disiplin.",
      "Kamu percaya hasil besar dimulai dari usaha-usaha kecil.",
      "Side hustle kamu jalan terus walau belum jadi cuan utama.",
      "Kamu gigih cari tambahan walau hasilnya belum signifikan.",
      "Kerja keras kamu konsisten, walau cuannya masih level receh.",
      "Kamu tau proses butuh waktu, makanya tetap sabar usaha.",
      "Setiap peluang kecil kamu coba manfaatkan sebaik mungkin.",
      "Kamu jenis orang yang gak gampang nyerah walau cuan masih kecil.",
      "Hustle kamu nyata, walau hasilnya belum bikin kaya mendadak.",
      "Kamu percaya konsistensi lebih penting dari hasil instan.",
      "Usaha kecil-kecilan kamu jalanin dengan niat yang besar.",
      "Kamu rajin banget cari cuan tambahan di sela waktu luang.",
    ],
  },
  {
    nama: "Golongan Mendekati Sultan",
    deskripsi: [
      "Belum sultan, tapi udah keliatan arahnya kesana.",
      "Kamu udah di jalur yang benar buat jadi makin mapan.",
      "Progress finansial kamu kelihatan jelas, tinggal waktu aja.",
      "Kamu udah ngerasain manisnya hasil kerja keras selama ini.",
      "Tabungan kamu mulai terlihat, gaya hidup juga makin nyaman.",
      "Kamu di fase transisi dari struggling ke comfortable.",
      "Hasil usaha kamu mulai kelihatan, tinggal konsisten aja.",
      "Kamu udah ngerasa lebih stabil dibanding beberapa tahun lalu.",
      "Pelan-pelan kamu nuju ke level finansial yang lebih nyaman.",
      "Kamu udah ningkatin gaya hidup tanpa harus khawatir berlebihan.",
      "Investasi dan usaha kamu mulai kasih hasil yang terasa.",
      "Kamu udah bisa nabung sambil tetap nikmatin hidup.",
      "Progres kamu konsisten, sultan tinggal soal waktu.",
      "Kamu makin dekat sama level finansial yang kamu impikan.",
      "Kerja keras kamu selama ini mulai membuahkan hasil nyata.",
      "Kamu udah ningkatin standar hidup tanpa kehilangan kendali.",
      "Tinggal sedikit lagi buat sampai di level yang kamu mau.",
      "Kamu udah ngerasain hasil dari disiplin yang dijalani konsisten.",
      "Finansialmu makin solid, arah ke sultan makin jelas.",
      "Kamu di track yang tepat buat jadi lebih mapan ke depannya.",
    ],
  },
  {
    nama: "Golongan Cuan Mengalir",
    deskripsi: [
      "Rezeki dateng dari berbagai arah, syukur jalan terus.",
      "Kamu punya banyak sumber cuan yang saling melengkapi.",
      "Pemasukan kamu lancar dari berbagai jalur yang udah dirintis.",
      "Kamu jago manfaatin peluang dari mana aja buat nambah cuan.",
      "Rezeki kamu gak cuma dari satu sumber, tapi banyak arah.",
      "Kamu udah punya sistem yang bikin uang terus mengalir.",
      "Setiap usaha yang kamu rintis mulai kasih hasil yang stabil.",
      "Cuan kamu lancar karena kamu jago diversifikasi sumber income.",
      "Kamu tau caranya bikin uang kerja buat kamu, bukan sebaliknya.",
      "Pemasukan kamu konsisten dan terus berkembang dari waktu ke waktu.",
      "Kamu udah ngerasain hasil dari kerja keras yang terstruktur.",
      "Banyak pintu rezeki yang kamu buka dan kelola dengan baik.",
      "Kamu jenis orang yang rezekinya datang dari berbagai usaha.",
      "Cuan kamu gak cuma sekali datang, tapi terus mengalir stabil.",
      "Kamu udah ningkatin kualitas hidup berkat usaha yang variatif.",
      "Setiap bulan cuan kamu makin terasa dan makin stabil.",
      "Kamu jago banget bikin uang bekerja sambil kamu istirahat.",
      "Rezeki lancar karena kamu rajin nyiapin banyak jalur usaha.",
      "Kamu udah di level yang nyaman secara finansial dan terus naik.",
      "Cuan kamu konsisten karena dikelola dengan strategi yang matang.",
    ],
  },
  {
    nama: "Golongan OKB Beneran",
    deskripsi: [
      "Orang Kaya Baru yang prestasinya emang nyata.",
      "Kekayaanmu hasil kerja keras, bukan cuma keberuntungan sesaat.",
      "Kamu naik kelas finansial dengan usaha yang konsisten.",
      "Statusmu sebagai OKB didapat dari proses yang panjang.",
      "Kamu udah buktiin kalau kerja keras emang berbuah hasil.",
      "Kekayaan kamu sekarang hasil dari perjuangan yang gak instan.",
      "Kamu udah naik level dan layak nikmatin hasilnya.",
      "Prestasi finansialmu nyata, bukan cuma pencitraan doang.",
      "Kamu udah buktiin kalau usaha keras gak pernah bohong.",
      "Status barumu didapat dengan kerja keras yang konsisten.",
      "Kamu udah ningkatin taraf hidup lewat usaha yang nyata.",
      "Kekayaanmu terlihat, dan prosesnya juga bisa dipertanggungjawabkan.",
      "Kamu udah jadi bukti hidup kalau usaha keras berbuah manis.",
      "Naik kelas finansial kamu dapatkan lewat jalan yang halal dan kerja keras.",
      "Kamu udah ningkatin kualitas hidup secara signifikan dari sebelumnya.",
      "Pencapaian kamu nyata, bukan cuma gimmick di media sosial.",
      "Kamu udah ngerasain hasil dari dedikasi yang panjang.",
      "Status OKB kamu sah karena emang lewat proses yang jujur.",
      "Kamu udah jadi inspirasi buat orang yang mau naik level juga.",
      "Kekayaanmu sekarang adalah hasil dari konsistensi yang panjang.",
    ],
  },
  {
    nama: "Golongan Sultan Tanpa Beban",
    deskripsi: [
      "Hidup udah di level santuy karena emang udah aman.",
      "Kamu bebas mikirin hal lain karena finansial udah stabil.",
      "Kestabilan finansialmu bikin hidup terasa lebih ringan.",
      "Kamu udah di level yang gak perlu khawatir soal uang lagi.",
      "Hidupmu santai karena pondasi finansial udah kuat.",
      "Kamu udah bisa nikmatin hidup tanpa beban finansial berlebihan.",
      "Kestabilanmu bikin kamu bisa fokus ke hal-hal lain yang penting.",
      "Kamu udah di posisi yang nyaman dan gak gampang khawatir.",
      "Finansial yang aman bikin hidupmu jauh lebih tenang.",
      "Kamu udah ngerasain kemewahan ketenangan karena uang udah aman.",
      "Hidupmu santai karena udah gak perlu mikirin hal-hal dasar.",
      "Kamu bisa fokus ke passion karena urusan uang udah beres.",
      "Kestabilan finansial kamu bikin pilihan hidup jadi lebih bebas.",
      "Kamu udah di level yang banyak orang impikan: tenang dan cukup.",
      "Hidupmu jauh dari drama finansial yang biasa orang lain alami.",
      "Kamu bisa santai karena fondasi hidupmu udah kuat banget.",
      "Kestabilanmu jadi privilege yang kamu manfaatkan dengan bijak.",
      "Kamu udah ngerasain hasil kerja keras yang bikin hidup lebih ringan.",
      "Finansial aman bikin kamu lebih leluasa nikmatin hidup.",
      "Kamu udah di level sultan yang santuy tanpa banyak beban pikiran.",
    ],
  },
  {
    nama: "Golongan Bertahan Hidup Doang",
    deskripsi: [
      "Targetnya simpel: survive sampai akhir bulan.",
      "Kamu fokus bertahan, urusan lain dipikir belakangan.",
      "Hidupmu sekarang prioritasnya cuma satu: tetap aman.",
      "Kamu jago bertahan walau situasi gak selalu mendukung.",
      "Survival mode kamu nyala terus, gak pernah off.",
      "Kamu paham banget gimana caranya cukup di kondisi terbatas.",
      "Setiap hari adalah perjuangan kecil buat tetap stabil.",
      "Kamu gak mikir muluk-muluk, yang penting hari ini aman.",
      "Bertahan hidup udah jadi skill utama yang kamu kuasai.",
      "Kamu tau caranya tetap jalan walau resource terbatas.",
      "Fokus utama kamu adalah memastikan kebutuhan dasar terpenuhi.",
      "Kamu gak banyak menuntut, yang penting bisa lewatin hari ini.",
      "Survival adalah kata yang paling pas buat gambarkan hidupmu sekarang.",
      "Kamu kuat banget dalam menghadapi keterbatasan sehari-hari.",
      "Setiap rupiah dipikir matang demi bertahan sampai akhir bulan.",
      "Kamu paham banget arti kata cukup dalam situasi yang serba terbatas.",
      "Hidupmu fokus ke hal dasar, mimpi besar nanti dulu.",
      "Kamu jago adaptasi sama kondisi yang gak selalu ideal.",
      "Bertahan adalah pencapaian buat kamu di kondisi sekarang.",
      "Kamu kuat menjalani hari demi hari tanpa banyak mengeluh.",
    ],
  },
  {
    nama: "Golongan Ngarep Tapi Santai",
    deskripsi: [
      "Berharap hal baik terjadi, tapi gak maksa diri.",
      "Kamu optimis tapi tetap realistis sama kemungkinan.",
      "Berharap boleh, ngoyo nggak perlu.",
      "Kamu santai nunggu hasil baik tanpa terlalu ngebut ngejarnya.",
      "Harapanmu tinggi, tapi caramu mencapainya tetap kalem.",
      "Kamu percaya hal baik akan datang pada waktunya.",
      "Ngarep itu manusiawi, dan kamu jalanin dengan tenang.",
      "Kamu gak buru-buru, tapi tetap punya harapan yang jelas.",
      "Optimisme kamu santai, gak bikin kamu cemas berlebihan.",
      "Kamu percaya usaha pelan-pelan tetap bisa nyampe tujuan.",
      "Harapan kamu realistis, gak muluk-muluk tapi tetap ada.",
      "Kamu jalanin hidup dengan harapan yang gak bikin tertekan.",
      "Berharap baik itu wajar, dan kamu jalanin tanpa drama.",
      "Kamu tau caranya berharap tanpa kehilangan ketenangan.",
      "Optimisme kamu seimbang sama kesabaran yang kamu punya.",
      "Kamu percaya semua bakal baik-baik aja pada waktunya.",
      "Harapanmu nyata, tapi gak bikin kamu jadi terlalu cemas.",
      "Kamu santai aja menunggu hasil terbaik dari usahamu.",
      "Ngarep versimu adalah harapan yang realistis dan tenang.",
      "Kamu percaya semesta bekerja dengan caranya sendiri.",
    ],
  },
  {
    nama: "Golongan Capek Tapi Lanjut",
    deskripsi: [
      "Lelah iya, berhenti nanti dulu.",
      "Kamu capek, tapi tetap jalan karena tau harus gitu.",
      "Lelah fisik dan mental, tapi semangat buat lanjut tetap ada.",
      "Kamu gak berhenti walau rasanya udah pengin rebahan total.",
      "Capek itu nyata, tapi kamu tetap pilih buat terus maju.",
      "Kamu jago bertahan walau energi udah mulai menipis.",
      "Setiap hari berat, tapi kamu tetap jalanin dengan gigih.",
      "Kamu capek, tapi tanggung jawab bikin kamu tetap bergerak.",
      "Lelah kamu nyata, tapi semangat juang juga gak pernah hilang.",
      "Kamu paham capek itu wajar, asal jangan berhenti total.",
      "Setiap rasa lelah kamu lawan dengan tekad buat tetap lanjut.",
      "Kamu tau istirahat penting, tapi tanggung jawab juga harus jalan.",
      "Capek bukan alasan buat kamu nyerah sepenuhnya.",
      "Kamu kuat menjalani hari yang berat dengan tetap maju.",
      "Energi menipis, tapi tekad kamu tetap full buat lanjut.",
      "Kamu jenis orang yang capek tapi tetap setia sama komitmen.",
      "Lelah kamu real, tapi kamu gak kasih ruang buat nyerah.",
      "Kamu tau cara push diri walau rasanya udah pengin istirahat aja.",
      "Capek itu sinyal, tapi kamu tetap pilih buat terus melangkah.",
      "Kamu kuat bertahan walau rasanya pengin berhenti sebentar.",
    ],
  },
  {
    nama: "Golongan Tukang PHP Diri Sendiri",
    deskripsi: [
      "Janji ke diri sendiri paling sering diingkari.",
      "Kamu spesialis bikin komitmen yang gampang dilanggar sendiri.",
      "Resolusi kamu banyak, tapi yang jalan cuma sedikit.",
      "Kamu jago kasih harapan ke diri sendiri, susah nepatinnya.",
      "Setiap 'besok mulai diet' selalu jadi cerita lama yang berulang.",
      "Kamu bikin target, tapi diri sendiri yang paling sering dikecewain.",
      "Niat kamu kuat di awal, eksekusinya selalu butuh negosiasi ulang.",
      "Kamu paham banget rasanya nge-PHP-in diri sendiri berkali-kali.",
      "Komitmen ke diri sendiri kamu butuh banyak revisi.",
      "Kamu jenis orang yang ahli kasih alasan kenapa rencana ditunda lagi.",
      "Setiap rencana besar berakhir jadi obrolan doang.",
      "Kamu suka bikin target ambisius, realisasinya selalu mundur.",
      "Diri sendiri jadi korban utama dari kebiasaan menunda kamu.",
      "Kamu jago meyakinkan diri sendiri buat mulai lagi besok.",
      "Setiap janji ke diri sendiri punya track record yang kurang konsisten.",
      "Kamu paham banget siklus niat-gagal-niat lagi yang berulang.",
      "Komitmen kamu kuat di teori, lemah di praktiknya.",
      "Kamu sering kecewa sama diri sendiri soal target yang gak tercapai.",
      "Setiap awal bulan jadi momen reset janji yang sama berulang kali.",
      "Kamu jago menjanjikan, kurang jago menepatinya ke diri sendiri.",
    ],
  },
  {
    nama: "Golongan Mendadak Bijak",
    deskripsi: [
      "Kadang random ngomong bijak padahal hidup berantakan.",
      "Kamu bisa kasih nasihat keren walau hidup sendiri kacau.",
      "Quote bijak keluar otomatis, walau prakteknya masih belajar.",
      "Kamu jago kasih insight, tapi belum tentu jalanin sendiri.",
      "Omongan kamu dalem, kenyataan hidup kamu kadang berantakan.",
      "Kamu bisa jadi tempat curhat orang, tapi masalah sendiri numpuk.",
      "Nasihat kamu manjur buat orang lain, buat diri sendiri belum tentu.",
      "Kamu sering dapat pencerahan dadakan di tengah hidup yang chaos.",
      "Kata-kata bijakmu keluar pas momen yang gak terduga.",
      "Kamu jago analisa masalah orang, masalah sendiri kadang terabaikan.",
      "Insight kamu tajam, walau prakteknya masih perlu effort lebih.",
      "Kamu bisa motivasi orang lain walau motivasi diri sendiri naik turun.",
      "Kebijaksanaan kamu muncul random di tengah drama hidup sendiri.",
      "Kamu jenis orang yang teorinya kuat, praktiknya masih proses.",
      "Nasihatmu sering jadi quote yang dibagi-bagi orang lain.",
      "Kamu bisa liat masalah dari sudut yang jernih, walau hidup sendiri rumit.",
      "Insight dadakan kamu sering muncul pas lagi nyantai aja.",
      "Kamu jago kasih perspektif baru, walau buat diri sendiri masih belajar.",
      "Kebijaksanaanmu nyata, walau aplikasinya ke diri sendiri masih proses.",
      "Kamu sering jadi sumber motivasi orang lain di tengah hidup yang berantakan.",
    ],
  },
  {
    nama: "Golongan Modal Nekat",
    deskripsi: [
      "Rencana belum matang, tapi jalan duluan aja.",
      "Kamu lebih percaya aksi daripada kelamaan mikir.",
      "Nekat jadi strategi utama kamu buat ambil keputusan.",
      "Kamu jalan duluan, mikirin detail belakangan.",
      "Keberanian kamu sering lebih besar dari persiapan yang ada.",
      "Kamu tipe yang action dulu, evaluasi belakangan.",
      "Modal nekat jadi senjata utama kamu hadapi ketidakpastian.",
      "Kamu percaya pengalaman lebih berharga dari rencana sempurna.",
      "Setiap keputusan besar kamu ambil dengan keberanian penuh.",
      "Kamu jenis orang yang loncat duluan, baru cari jaring pengaman.",
      "Persiapan minim gak bikin kamu ragu buat mulai.",
      "Kamu percaya jalan ketemu sambil jalan, bukan sambil diem.",
      "Keberanianmu jadi modal utama waktu yang lain masih ragu-ragu.",
      "Kamu suka ambil risiko walau belum semua terencana sempurna.",
      "Nekat kamu bukan asal-asalan, tapi keyakinan kalau usaha pasti ada jalan.",
      "Kamu jago hadapi ketidakpastian dengan tetap melangkah maju.",
      "Setiap langkah besar kamu ambil tanpa banyak rasa takut.",
      "Kamu percaya pengalaman lapangan lebih berharga dari teori semata.",
      "Modal terbesar kamu adalah keberanian buat coba duluan.",
      "Kamu jalan dengan keyakinan, walau detailnya belum semua jelas.",
    ],
  },
  {
    nama: "Golongan Pejuang Tanggal Tua",
    deskripsi: [
      "Tanggal 25 ke atas adalah arena pertarungan sesungguhnya.",
      "Kamu jago survive di hari-hari terakhir sebelum gajian.",
      "Tanggal tua adalah ujian kesabaran finansial terberat tiap bulan.",
      "Kamu udah punya jurus khusus buat lewatin minggu terakhir bulan.",
      "Setiap akhir bulan jadi medan perjuangan yang kamu hadapi tegar.",
      "Kamu paham banget rasanya kreatif cari makan di tanggal tua.",
      "Strategi survival kamu paling teruji di hari-hari sebelum gajian.",
      "Kamu jago banget irit di saat-saat genting akhir bulan.",
      "Tanggal tua bukan momok, itu rutinitas yang kamu hadapi dengan tenang.",
      "Kamu punya banyak trik buat tetap makan enak walau budget terbatas.",
      "Setiap bulan kamu lewati siklus yang sama dengan kesabaran penuh.",
      "Kamu jenis pejuang sejati di minggu-minggu terakhir sebelum gajian.",
      "Kreativitas kamu meningkat drastis pas dompet menipis di akhir bulan.",
      "Kamu udah hafal banget rasanya nahan diri di tanggal-tanggal kritis.",
      "Setiap tanggal tua kamu hadapi dengan jurus survival andalan.",
      "Kamu jago banget manfaatin sisa stok demi bertahan sampai gajian.",
      "Perjuanganmu di akhir bulan udah jadi rutinitas yang kamu kuasai.",
      "Kamu paham banget seni bertahan hidup di hari-hari kritis bulanan.",
      "Setiap akhir bulan kamu lewati dengan strategi yang udah teruji.",
      "Kamu veteran dalam menghadapi tantangan finansial tanggal tua.",
    ],
  },
  {
    nama: "Golongan Anti Mainstream",
    deskripsi: [
      "Pilihan hidupmu emang beda dari kebanyakan orang.",
      "Kamu jalan dengan caramu sendiri, gak ikut arus umum.",
      "Standar normal orang lain gak selalu jadi acuan buatmu.",
      "Kamu percaya jalan sendiri lebih cocok daripada ngikutin tren.",
      "Pilihan hidupmu unik dan jarang ditemui di kebanyakan orang.",
      "Kamu gak takut beda walau itu artinya jalan sendirian.",
      "Caramu hidup gak ngikutin pola yang biasa orang jalani.",
      "Kamu lebih nyaman dengan jalur yang kamu bikin sendiri.",
      "Pilihan kamu sering bikin orang lain bertanya-tanya, tapi kamu yakin.",
      "Kamu percaya hidup gak harus sama kayak orang kebanyakan.",
      "Jalan hidupmu unik dan punya cerita yang berbeda dari biasanya.",
      "Kamu berani ambil keputusan yang gak populer tapi sesuai diri sendiri.",
      "Kamu jenis orang yang gak ngikutin standar sosial secara membabi buta.",
      "Pilihan hidupmu mencerminkan keberanian buat jadi diri sendiri.",
      "Kamu nyaman jalan beda walau kadang dipertanyakan orang sekitar.",
      "Caramu menjalani hidup gak ngikutin template yang umum dilihat.",
      "Kamu percaya keunikan lebih berharga dari sekedar ikut-ikutan.",
      "Pilihan hidupmu otentik, jauh dari pola yang biasa diikuti orang.",
      "Kamu berani tampil beda dalam menentukan arah hidup sendiri.",
      "Jalanmu sendiri, dan kamu yakin sama keputusan yang kamu ambil.",
    ],
  },
  {
    nama: "Golongan Investor Receh",
    deskripsi: [
      "Mulai investasi dari nominal kecil, tapi konsisten.",
      "Kamu percaya investasi gak harus nunggu modal besar dulu.",
      "Setiap nominal kecil kamu sisihkan secara rutin buat masa depan.",
      "Kamu mulai dari receh, tapi konsistensinya yang jadi kekuatan.",
      "Investasi kecil-kecilan kamu jalanin dengan disiplin yang baik.",
      "Kamu paham compound interest dimulai dari langkah kecil dulu.",
      "Setiap bulan kamu sisihkan sedikit demi sedikit buat investasi.",
      "Kamu jago mulai dari yang kecil tanpa nunggu kondisi ideal.",
      "Investasi receh kamu jalanin dengan pemahaman yang cukup matang.",
      "Kamu percaya konsistensi kecil lebih baik dari nekat modal besar.",
      "Setiap rupiah yang kamu investasikan punya tujuan jangka panjang.",
      "Kamu jenis orang yang sabar nunggu hasil dari proses kecil.",
      "Disiplin investasi kamu udah jadi kebiasaan yang terjaga rutin.",
      "Kamu mulai belajar instrumen investasi walau modalnya masih kecil.",
      "Setiap penghasilan kamu sisihkan sebagian buat masa depan.",
      "Kamu paham investasi itu marathon, bukan sprint sesaat.",
      "Langkah kecil kamu di investasi udah jadi pondasi yang baik.",
      "Kamu rajin belajar soal keuangan walau praktiknya masih bertahap.",
      "Investasi receh kamu jalanin dengan niat yang serius dan jangka panjang.",
      "Kamu percaya proses kecil yang konsisten bakal jadi besar nantinya.",
    ],
  },
  {
    nama: "Golongan Crazy Rich Receh",
    deskripsi: [
      "Gaya hidup sultan, kantong masih menyesuaikan.",
      "Kamu flexing kayak crazy rich, tapi realitanya masih dicicil.",
      "Penampilan mewah, tapi dompet kadang minta diskon dulu.",
      "Kamu hidup di standar tinggi walau budget belum sepenuhnya nyampe.",
      "Gaya hidupmu udah level atas, finansial masih level menengah.",
      "Kamu jago tampil mewah walau di balik layar harus pintar atur.",
      "Citra crazy rich kamu kuat, walau realitanya tetap perlu strategi.",
      "Kamu paham caranya kelihatan mapan walau usahanya masih jalan.",
      "Gaya hidup tinggi, tapi kamu tetap pintar cari diskon dan promo.",
      "Kamu hidup mewah secara penampilan, realistis secara perencanaan.",
      "Setiap barang branded kamu punya, tapi tetap mikir cara bayarnya.",
      "Kamu jago bikin orang lain ngira kamu udah settle secara finansial.",
      "Gaya hidup sultan kamu jalanin walau modalnya masih usaha keras.",
      "Kamu paham gimana caranya kelihatan kaya tanpa kebablasan boros.",
      "Penampilan crazy rich kamu nyata, dompetnya tetap perlu strategi.",
      "Kamu jago balance antara gaya hidup tinggi dan kemampuan riil.",
      "Citra mewahmu kuat, walau di belakang tetap kerja keras buat nutupin.",
      "Kamu hidup di level estetika tinggi walau anggarannya tetap diatur ketat.",
      "Setiap flexing kamu punya cerita usaha keras di baliknya.",
      "Kamu pintar banget jaga image tanpa bikin keuangan jadi berantakan.",
    ],
  },
];

export function pilihDeskripsiAcak(golongan) {
  if (!golongan || !golongan.deskripsi || golongan.deskripsi.length === 0) {
    return "";
  }
  const idx = Math.floor(Math.random() * golongan.deskripsi.length);
  return golongan.deskripsi[idx];
}

export function hitungSkorTotal(jawaban, bagianData) {
  let total = 0;
  for (const bagian of bagianData) {
    for (const p of bagian.pertanyaan) {
      const jawabanTeks = jawaban[p.id];
      if (!jawabanTeks) continue;
      const opsiIndex = p.opsi.indexOf(jawabanTeks);
      if (opsiIndex !== -1 && BOBOT_SKOR[p.id]) {
        total += BOBOT_SKOR[p.id][opsiIndex] || 3;
      } else {
        total += 3; // fallback netral kalau jawaban gak match (seharusnya gak terjadi)
      }
    }
  }
  return total;
}

export function tentukanGolongan(skorTotal) {
  // Breakpoint ini dihitung dari simulasi distribusi skor aktual (40 pertanyaan,
  // bobot riil di atas), bukan rentang linear MIN-MAX. Ini memastikan 30 golongan
  // terbagi rata secara persentil, jadi jawaban acak ATAU konsisten tetap menyebar
  // ke berbagai golongan, bukan numpuk di golongan tengah.
  const BREAKPOINTS = [
    77, 88, 92, 95, 97, 99, 100, 102, 103, 104,
    105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
    115, 116, 118, 119, 121, 123, 126, 130, 136,
  ];

  let index = 0;
  for (let i = 0; i < BREAKPOINTS.length; i++) {
    if (skorTotal > BREAKPOINTS[i]) {
      index = i + 1;
    } else {
      break;
    }
  }
  index = Math.min(GOLONGAN.length - 1, Math.max(0, index));
  return GOLONGAN[index];
}
