// Rekomendasi/solusi satir ala "kebijakan negara" untuk tiap golongan
// 20 variasi per golongan, dipilih acak saat ditampilkan (sama pola dengan deskripsi)
// Key harus sama persis dengan "nama" golongan di golonganData.js

export const REKOMENDASI = {
  "Golongan Rebahan Mutlak": [
    "Anda berhak menerima Bantuan Langsung Tunai (BLT) khusus kasur dan bantal.",
    "Anda direkomendasikan ikut program transmigrasi dari kasur ke sofa, demi variasi.",
    "Negara menyarankan Anda daftar BPJS khusus pegal-pegal akibat rebahan kelamaan.",
    "Anda layak menerima piagam 'Pahlawan Tanpa Gerak' dari Kementerian Kasur.",
    "Pemerintah mengusulkan subsidi listrik khusus charger HP di samping kasur Anda.",
    "Anda direkomendasikan ikut pelatihan dasar: cara duduk tegak selama 5 menit.",
    "Negara memberi izin resmi untuk tetap rebahan, asal jangan lupa makan.",
    "Anda berhak atas penghargaan 'Warga Paling Setia Sama Kasur Tahun Ini'.",
    "Pemerintah menyarankan Anda pasang roda di kasur biar mobilitas naik sedikit.",
    "Anda direkomendasikan terapi gerak ringan: minimal duduk dulu sebelum tidur lagi.",
    "Negara mengusulkan kasur Anda didaftarkan sebagai aset properti tetap.",
    "Anda layak dapat sertifikat 'Ahli Rebahan Bersertifikat Nasional'.",
    "Pemerintah menyarankan evaluasi ulang: apakah kasur atau Anda yang lebih produktif.",
    "Anda direkomendasikan ikut program 'Sehari Tanpa Rebahan', walau gagal duluan.",
    "Negara memberi dispensasi khusus: boleh rebahan asal sambil mikirin masa depan.",
    "Anda berhak menerima bantal tambahan sebagai apresiasi dari Kementerian Kenyamanan.",
    "Pemerintah mengusulkan riset: berapa kalori terbakar saat geser posisi tidur.",
    "Anda direkomendasikan jadi duta resmi gerakan 'Mager Itu Hak Asasi'.",
    "Negara menyarankan Anda tetap rebahan, tapi sambil baca buku biar berkesan produktif.",
    "Anda layak dapat penghargaan 'Paling Setia Sama Selimut Sepanjang Tahun'.",
  ],
  "Golongan Pasrah Sejati": [
    "Anda direkomendasikan jadi penasihat ketenangan untuk warga yang gampang panik.",
    "Negara menyarankan Anda buka kelas 'Cara Pasrah yang Sehat dan Tenang'.",
    "Anda berhak menerima sertifikat 'Master Zen Tanpa Sertifikasi Resmi'.",
    "Pemerintah mengusulkan Anda jadi mediator damai untuk drama keluarga tetangga.",
    "Anda direkomendasikan ikut program 'Influencer Ketenangan Batin Nasional'.",
    "Negara menyarankan ketenangan Anda dipatenkan sebagai aset budaya daerah.",
    "Anda layak dapat gelar kehormatan 'Warga Paling Susah Diajak Ribut'.",
    "Pemerintah mengusulkan Anda jadi konselor gratis buat yang overthinking.",
    "Anda direkomendasikan ikut riset: rahasia ketenangan tanpa terapi mahal.",
    "Negara menyarankan Anda diundang jadi pembicara seminar 'Hidup Tanpa Drama'.",
    "Anda berhak menerima penghargaan 'Manusia Paling Jarang Emosi Tahun Ini'.",
    "Pemerintah mengusulkan ketenangan Anda jadi bahan kajian psikologi nasional.",
    "Anda direkomendasikan jadi maskot kampanye 'Santai Itu Sehat'.",
    "Negara menyarankan Anda buka jasa konsultasi 'Cara Ikhlas dalam 5 Menit'.",
    "Anda layak dapat sertifikat partisipasi acara 'Festival Kepasrahan Tahunan'.",
    "Pemerintah mengusulkan Anda jadi narasumber podcast soal mental health.",
    "Anda direkomendasikan ikut pelatihan lanjutan: pasrah tapi tetap produktif.",
    "Negara menyarankan ketenangan Anda dibagikan gratis ke warga yang stres.",
    "Anda berhak menerima medali 'Juara Hidup Tanpa Banyak Mengeluh'.",
    "Pemerintah mengusulkan Anda jadi role model nasional soal menerima kenyataan.",
  ],
  "Golongan Boncos Kronis": [
    "Anda mendapat subsidi darurat dari pemerintah berupa nasihat: 'sabar ya, tanggal tua emang gini'.",
    "Negara merekomendasikan Anda ikut program literasi keuangan tingkat dasar, dua kali.",
    "Anda berhak menerima sertifikat 'Pelanggan Setia Promo Tanggal Muda'.",
    "Pemerintah mengusulkan Anda dapat kartu diskon khusus mie instan akhir bulan.",
    "Anda direkomendasikan ikut pelatihan 'Cara Bilang Tidak ke Diskon Flash Sale'.",
    "Negara menyarankan rekening Anda diberi label peringatan: 'Rawan Boncos'.",
    "Anda layak menerima penghargaan 'Paling Konsisten Boncos Setiap Bulan'.",
    "Pemerintah mengusulkan riset nasional soal siklus boncos bulanan Anda.",
    "Anda direkomendasikan ikut grup dukungan 'Korban Self-Reward Berlebihan'.",
    "Negara menyarankan Anda pasang alarm khusus: 'Awas, Mau Checkout Lagi'.",
    "Anda berhak menerima voucher gratis konsultasi keuangan, walau jarang dipakai.",
    "Pemerintah mengusulkan Anda jadi studi kasus 'Antara Gaji dan Keinginan'.",
    "Anda direkomendasikan menempel stiker di dompet: 'Pikir Dua Kali'.",
    "Negara menyarankan Anda ikut tantangan 'No Spend Challenge', walau gagal hari ke-2.",
    "Anda layak dapat gelar 'Ahli Bertahan Hidup di Tanggal Tua'.",
    "Pemerintah mengusulkan diskon khusus warga yang sering checkout impulsif.",
    "Anda direkomendasikan menabung dengan sistem paksa, biar gak kebablasan lagi.",
    "Negara menyarankan Anda jadi bahan edukasi 'Kenapa Tabungan Susah Naik'.",
    "Anda berhak menerima motivasi gratis dari Kementerian Dompet Kering.",
    "Pemerintah mengusulkan Anda pasang reminder: 'Inget, Masih Tanggal 10'.",
  ],
  "Golongan Numpang Hidup": [
    "Anda berhak menerima sertifikat 'Ahli Manfaatin Privilege Keluarga Tahun Ini'.",
    "Negara merekomendasikan Anda mulai cicil rasa terima kasih ke orang tua.",
    "Pemerintah mengusulkan Anda ikut pelatihan dasar 'Cara Mandiri untuk Pemula'.",
    "Anda direkomendasikan menyusun rencana keluar dari zona nyaman keluarga.",
    "Negara menyarankan Anda diberi semangat: 'Gak apa numpang, asal ada progress'.",
    "Anda berhak menerima penghargaan 'Paling Setia Sama Subsidi Orang Tua'.",
    "Pemerintah mengusulkan Anda mulai cari penghasilan, walau dari hal kecil.",
    "Anda direkomendasikan ikut kelas motivasi 'Saatnya Berdiri di Kaki Sendiri'.",
    "Negara menyarankan Anda jadi duta kampanye 'Mandiri Itu Keren'.",
    "Anda layak dapat dukungan moral dari Kementerian Kemandirian Finansial.",
    "Pemerintah mengusulkan Anda buat target kecil: cari uang sendiri bulan ini.",
    "Anda direkomendasikan tetap bersyukur, tapi mulai mikirin masa depan juga.",
    "Negara menyarankan Anda ikut program magang biar ada pengalaman kerja.",
    "Anda berhak menerima nasihat gratis: 'Numpang itu wajar, tapi jangan lama-lama'.",
    "Pemerintah mengusulkan Anda mulai nabung dari sisa uang yang dikasih.",
    "Anda direkomendasikan jadi bahan refleksi: kapan waktunya mandiri.",
    "Negara menyarankan Anda ikut seminar 'Dari Numpang ke Mapan'.",
    "Anda layak dapat sertifikat partisipasi 'Warga yang Masih Belajar Mandiri'.",
    "Pemerintah mengusulkan Anda diberi tantangan kecil: cari cuan receh dulu.",
    "Anda direkomendasikan tetap nyaman, tapi siapkan rencana jangka panjang.",
  ],
  "Golongan PHP Sepanjang Masa": [
    "Anda direkomendasikan ikut seminar 'Dari Niat ke Aksi', minimal coba dateng.",
    "Negara menyarankan Anda buat to-do list yang lebih realistis, bukan ambisius.",
    "Anda berhak menerima sertifikat 'Paling Jago Bikin Rencana, Belum Jago Jalanin'.",
    "Pemerintah mengusulkan Anda dipasangkan reminder otomatis tiap pagi.",
    "Anda direkomendasikan coba metode 5 menit: mulai aja dulu, mikirnya belakangan.",
    "Negara menyarankan resolusi tahun baru Anda dipersingkat jadi satu poin saja.",
    "Anda layak dapat penghargaan 'Wacana Terbanyak Tahun Ini'.",
    "Pemerintah mengusulkan Anda ikut program 'Eksekusi 1%', sehari satu langkah kecil.",
    "Anda direkomendasikan tempel kertas 'MULAI SEKARANG' di tempat strategis.",
    "Negara menyarankan Anda evaluasi: kenapa niat selalu kalah sama rasa males.",
    "Anda berhak menerima dukungan moral dari Kementerian Realisasi Rencana.",
    "Pemerintah mengusulkan Anda dikasih deadline ketat biar terpaksa gerak.",
    "Anda direkomendasikan ikut kelas 'Cara Menepati Janji ke Diri Sendiri'.",
    "Negara menyarankan Anda mulai dari hal kecil dulu, bukan target besar.",
    "Anda layak dapat sertifikat 'Spesialis Menunda Tanpa Rasa Bersalah'.",
    "Pemerintah mengusulkan Anda buat sistem reward kecil tiap selesai satu tugas.",
    "Anda direkomendasikan jujur ke diri sendiri: ini niat atau cuma wacana.",
    "Negara menyarankan Anda cari teman yang bisa nagih progress harian.",
    "Anda berhak menerima motivasi gratis: 'Yuk, mulai dari sekarang aja'.",
    "Pemerintah mengusulkan Anda ikut tantangan 30 hari konsisten, walau berat.",
  ],
  "Golongan Mager Akut": [
    "Anda direkomendasikan ikut terapi gerak ringan: jalan ke dapur saja dulu.",
    "Negara menyarankan Anda dikasih kursi roda biar mobilitas naik sedikit.",
    "Anda berhak menerima sertifikat 'Paling Jago Cari Alasan Buat Gak Gerak'.",
    "Pemerintah mengusulkan delivery online jadi kebutuhan primer resmi Anda.",
    "Anda direkomendasikan ikut tantangan 'Sehari Tanpa Rebahan Total'.",
    "Negara menyarankan remote control TV Anda didaftarkan sebagai aset penting.",
    "Anda layak dapat penghargaan 'Juara Nasional Kategori Gak Mau Ribet'.",
    "Pemerintah mengusulkan riset: berapa lama Anda bisa diam di satu posisi.",
    "Anda direkomendasikan coba olahraga ringan, minimal stretching 2 menit.",
    "Negara menyarankan Anda jadi duta kampanye 'Mager Boleh, Asal Sadar Diri'.",
    "Anda berhak menerima bantuan moral dari Kementerian Produktivitas Minimal.",
    "Pemerintah mengusulkan Anda ikut program 'Gerak Dikit, Hidup Jadi Asik'.",
    "Anda direkomendasikan menempel target kecil: bangun jam segini, bukan jam segitu.",
    "Negara menyarankan Anda evaluasi ulang hubungan dengan sofa dan kasur.",
    "Anda layak dapat sertifikat 'Ahli Bertahan di Posisi yang Sama Lama Banget'.",
    "Pemerintah mengusulkan Anda dikasih jam alarm yang lebih galak.",
    "Anda direkomendasikan ikut kelas motivasi 'Bangun Itu Mudah, Coba Aja'.",
    "Negara menyarankan Anda jujur: ini mager atau emang capek beneran.",
    "Anda berhak menerima dukungan dari grup 'Sama-Sama Mager, Yuk Bangkit'.",
    "Pemerintah mengusulkan Anda coba gerak 10 menit sehari, pelan-pelan dulu.",
  ],
  "Golongan Receh Bahagia": [
    "Anda berhak menerima penghargaan 'Paling Jago Bersyukur dengan Hal Kecil'.",
    "Negara merekomendasikan kebahagiaan Anda dijadikan kurikulum wajib nasional.",
    "Pemerintah mengusulkan Anda jadi duta kampanye 'Bahagia Itu Murah'.",
    "Anda direkomendasikan ikut talkshow 'Cara Bahagia Tanpa Banyak Modal'.",
    "Negara menyarankan filosofi hidup Anda dipatenkan sebagai warisan budaya.",
    "Anda berhak dapat sertifikat 'Ahli Menemukan Kebahagiaan di Tempat Sederhana'.",
    "Pemerintah mengusulkan Anda jadi pembicara seminar syukur tingkat daerah.",
    "Anda direkomendasikan menulis buku 'Receh Tapi Bahagia: Panduan Hidup'.",
    "Negara menyarankan kebiasaan Anda ditiru oleh warga yang gampang stres.",
    "Anda layak menerima medali 'Paling Tenang Walau Dompet Pas-Pasan'.",
    "Pemerintah mengusulkan Anda jadi konsultan kebahagiaan gratis untuk tetangga.",
    "Anda direkomendasikan ikut riset nasional soal rahasia bahagia sederhana.",
    "Negara menyarankan Anda diundang jadi narasumber podcast self-love.",
    "Anda berhak dapat penghargaan 'Senyum Paling Tulus Meski Modal Minim'.",
    "Pemerintah mengusulkan filosofi hidup Anda diajarkan di sekolah dasar.",
    "Anda direkomendasikan jadi maskot kampanye 'Cukup Itu Lebih dari Cukup'.",
    "Negara menyarankan Anda dapat sertifikat kehormatan dari Kementerian Syukur.",
    "Anda berhak menerima apresiasi karena gak pernah ngeluh soal hidup sederhana.",
    "Pemerintah mengusulkan Anda jadi inspirasi nasional soal hidup minimalis.",
    "Anda direkomendasikan tetap jaga kebahagiaan receh ini selamanya.",
  ],
  "Golongan Halu Produktif": [
    "Anda direkomendasikan ikut program 'Dari Mimpi ke Aksi', kelas lanjutan.",
    "Negara menyarankan Anda buat roadmap biar mimpi besar gak cuma di kepala.",
    "Anda berhak menerima sertifikat 'Pemimpi yang Masih Mau Usaha'.",
    "Pemerintah mengusulkan Anda dikasih mentor biar progress makin cepat.",
    "Anda direkomendasikan tulis target jangka pendek biar mimpi besar kebagi rapi.",
    "Negara menyarankan imajinasi Anda dijadikan modal usaha yang nyata.",
    "Anda layak dapat penghargaan 'Paling Konsisten Mimpi Besar Sambil Usaha'.",
    "Pemerintah mengusulkan Anda ikut bootcamp percepatan realisasi mimpi.",
    "Anda direkomendasikan evaluasi progress tiap bulan biar gak cuma halu doang.",
    "Negara menyarankan Anda gabung komunitas yang punya visi serupa.",
    "Anda berhak menerima dukungan dari Kementerian Realisasi Mimpi Warga.",
    "Pemerintah mengusulkan Anda bikin vision board biar makin termotivasi.",
    "Anda direkomendasikan pecah mimpi besar jadi langkah-langkah kecil harian.",
    "Negara menyarankan Anda jadi contoh: halu boleh, asal jalan beneran.",
    "Anda layak dapat sertifikat 'Mimpi Tinggi, Usaha Juga Gak Kalah Tinggi'.",
    "Pemerintah mengusulkan Anda ikut pelatihan manajemen waktu buat kejar mimpi.",
    "Anda direkomendasikan tetap halu, tapi sambil nyicil tabungan buat modal.",
    "Negara menyarankan Anda jadi inspirasi: mimpi besar bukan cuma angan.",
    "Anda berhak menerima apresiasi karena gak cuma diam sama mimpi sendiri.",
    "Pemerintah mengusulkan Anda lanjut konsisten, progress kecil tetap progress.",
  ],
  "Golongan Santuy Berkelas": [
    "Anda direkomendasikan jadi mentor 'Cara Santai Tanpa Kehilangan Arah'.",
    "Negara menyarankan gaya hidup Anda dijadikan studi kasus manajemen stres.",
    "Anda berhak menerima sertifikat 'Ahli Rileks Tapi Tetap Produktif'.",
    "Pemerintah mengusulkan Anda jadi pembicara soal work-life balance.",
    "Anda direkomendasikan bagikan tips santai ke yang gampang panik.",
    "Negara menyarankan Anda jadi role model 'Chill Tapi Tetap On Track'.",
    "Anda layak dapat penghargaan 'Paling Tenang Tapi Tetap Punya Rencana'.",
    "Pemerintah mengusulkan Anda jadi konsultan gaya hidup seimbang.",
    "Anda direkomendasikan tetap pertahankan ritme santai yang produktif ini.",
    "Negara menyarankan Anda diundang jadi narasumber soal manajemen waktu.",
    "Anda berhak menerima sertifikat 'Master Kelas Santai Tapi Terkontrol'.",
    "Pemerintah mengusulkan filosofi hidup Anda diajarkan di kelas motivasi.",
    "Anda direkomendasikan jadi inspirasi buat yang terlalu keras sama diri sendiri.",
    "Negara menyarankan Anda dapat apresiasi karena bisa santai tanpa kacau.",
    "Anda layak dapat gelar 'Warga Paling Seimbang Antara Kerja dan Rileks'.",
    "Pemerintah mengusulkan Anda jadi duta kampanye 'Santai Itu Strategi'.",
    "Anda direkomendasikan tetap jaga keseimbangan ini sebagai kekuatan utama.",
    "Negara menyarankan Anda bagikan rahasia ketenangan ke warga yang stres.",
    "Anda berhak menerima penghargaan dari Kementerian Gaya Hidup Seimbang.",
    "Pemerintah mengusulkan Anda jadi panutan generasi yang gampang burnout.",
  ],
  "Golongan Cukup-Cukup Aja": [
    "Anda berhak menerima sertifikat 'Paling Stabil Tanpa Drama Berlebihan'.",
    "Negara menyarankan keseimbangan hidup Anda dijadikan acuan nasional.",
    "Pemerintah mengusulkan Anda jadi role model 'Hidup Pas, Hati Tenang'.",
    "Anda direkomendasikan jadi inspirasi buat yang terlalu ngoyo atau terlalu santai.",
    "Negara menyarankan Anda dikasih apresiasi karena gak gampang baper sama standar orang.",
    "Anda layak dapat penghargaan 'Warga Paling Realistis Tahun Ini'.",
    "Pemerintah mengusulkan Anda jadi pembicara soal kepuasan hidup sederhana.",
    "Anda direkomendasikan tetap jaga kestabilan ini sebagai pondasi yang kuat.",
    "Negara menyarankan filosofi 'cukup' Anda diajarkan di kelas finansial dasar.",
    "Anda berhak menerima sertifikat 'Ahli Menjaga Standar Hidup yang Wajar'.",
    "Pemerintah mengusulkan Anda jadi duta kampanye 'Gak Perlu Lebih, Cukup Aja'.",
    "Anda direkomendasikan bagikan cara pandang ini ke yang gampang insecure.",
    "Negara menyarankan Anda dapat apresiasi karena jarang banding-bandingin hidup.",
    "Anda layak dapat gelar 'Paling Jago Menerima Kondisi dengan Lapang Dada'.",
    "Pemerintah mengusulkan Anda jadi contoh hidup tanpa ekstrem berlebihan.",
    "Anda direkomendasikan tetap konsisten dengan standar yang realistis ini.",
    "Negara menyarankan Anda diundang jadi narasumber soal kepuasan hidup.",
    "Anda berhak menerima penghargaan dari Kementerian Keseimbangan Hidup.",
    "Pemerintah mengusulkan Anda jadi panutan buat warga yang terlalu ambisius.",
    "Anda direkomendasikan tetap syukuri apa yang udah pas-pas ini.",
  ],
  "Golongan Hemat Pangkal Survive": [
    "Anda berhak menerima sertifikat 'Ahli Bertahan dengan Budget Minim'.",
    "Negara merekomendasikan Anda jadi mentor finansial untuk warga boros.",
    "Pemerintah mengusulkan Anda jadi pembicara seminar 'Hemat Tanpa Pelit'.",
    "Anda direkomendasikan bagikan tips diskon dan promo ke tetangga sekitar.",
    "Negara menyarankan kebiasaan hemat Anda dijadikan kurikulum sekolah.",
    "Anda berhak dapat penghargaan 'Paling Disiplin Atur Keuangan Tahun Ini'.",
    "Pemerintah mengusulkan Anda jadi konsultan gratis soal manajemen uang.",
    "Anda direkomendasikan tetap pertahankan kebiasaan hemat ini ke depannya.",
    "Negara menyarankan Anda diundang jadi narasumber 'Cara Survive di Tanggal Tua'.",
    "Anda layak dapat sertifikat 'Master Strategi Bertahan dengan Budget Terbatas'.",
    "Pemerintah mengusulkan Anda jadi duta kampanye 'Hemat Itu Keren'.",
    "Anda direkomendasikan bagikan jurus hemat ke yang sering boncos.",
    "Negara menyarankan Anda dapat apresiasi karena realistis sama kemampuan sendiri.",
    "Anda berhak menerima medali 'Paling Jago Cari Cara Survive Tanpa Boros'.",
    "Pemerintah mengusulkan Anda jadi panutan finansial buat generasi muda.",
    "Anda direkomendasikan tetap disiplin, tapi sesekali boleh self-reward kecil.",
    "Negara menyarankan Anda diundang jadi pembicara workshop literasi keuangan.",
    "Anda berhak dapat penghargaan dari Kementerian Disiplin Finansial Warga.",
    "Pemerintah mengusulkan kebiasaan hemat Anda jadi standar nasional.",
    "Anda direkomendasikan tetap waspada, tapi jangan terlalu keras ke diri sendiri.",
  ],
  "Golongan Sibuk Tapi Bingung": [
    "Anda direkomendasikan ikut workshop 'Menemukan Arah di Tengah Kesibukan'.",
    "Negara menyarankan Anda evaluasi ulang prioritas hidup tiap akhir bulan.",
    "Anda berhak menerima sertifikat 'Paling Sibuk Tapi Masih Nyari Tujuan'.",
    "Pemerintah mengusulkan Anda konsultasi karier gratis biar arahnya jelas.",
    "Anda direkomendasikan coba teknik fokus: satu hal dulu, baru lanjut lainnya.",
    "Negara menyarankan Anda buat jurnal harian biar progress lebih terlihat.",
    "Anda layak dapat dukungan dari Kementerian Manajemen Waktu Nasional.",
    "Pemerintah mengusulkan Anda ikut pelatihan menentukan prioritas hidup.",
    "Anda direkomendasikan luangkan waktu buat refleksi, bukan cuma kerja terus.",
    "Negara menyarankan Anda cari mentor yang udah jelas arah hidupnya.",
    "Anda berhak menerima sertifikat 'Energik Tapi Masih Cari Peta Hidup'.",
    "Pemerintah mengusulkan Anda buat visi jangka panjang biar gak cuma reaktif.",
    "Anda direkomendasikan kurangi multitasking, fokus ke yang penting dulu.",
    "Negara menyarankan Anda ikut tes minat dan bakat biar lebih jelas arahnya.",
    "Anda layak dapat apresiasi karena kerja keras walau arahnya masih dicari.",
    "Pemerintah mengusulkan Anda ambil waktu istirahat buat mikir ulang tujuan.",
    "Anda direkomendasikan diskusi sama orang terdekat soal arah hidup.",
    "Negara menyarankan Anda jangan takut ubah arah kalau memang perlu.",
    "Anda berhak menerima dukungan dari grup 'Sibuk Tapi Tetap Mencari Makna'.",
    "Pemerintah mengusulkan Anda pelan-pelan susun rencana yang lebih terarah.",
  ],
  "Golongan Ambis Setengah Hati": [
    "Anda direkomendasikan ikut kelas 'Konsistensi untuk Pemula yang Gampang Nyerah'.",
    "Negara menyarankan Anda cari accountability partner biar gak gampang berhenti.",
    "Anda berhak menerima sertifikat 'Niat 100%, Eksekusi Masih Proses'.",
    "Pemerintah mengusulkan Anda ikut tantangan 21 hari konsisten satu kebiasaan.",
    "Anda direkomendasikan pecah target besar jadi langkah kecil yang lebih ringan.",
    "Negara menyarankan Anda evaluasi: di titik mana biasanya semangat mulai turun.",
    "Anda layak dapat dukungan dari Kementerian Konsistensi dan Daya Tahan.",
    "Pemerintah mengusulkan Anda buat sistem reward kecil tiap progress tercapai.",
    "Anda direkomendasikan kurangi target ambisius, fokus yang realistis dulu.",
    "Negara menyarankan Anda gabung komunitas yang saling menyemangati.",
    "Anda berhak menerima sertifikat 'Potensi Besar, Tinggal Nambah Stamina'.",
    "Pemerintah mengusulkan Anda ikut pelatihan manajemen motivasi jangka panjang.",
    "Anda direkomendasikan catat progress kecil biar keliatan kemajuannya.",
    "Negara menyarankan Anda jangan terlalu keras ke diri sendiri saat gagal sedikit.",
    "Anda layak dapat apresiasi karena selalu berani mulai walau sering goyah.",
    "Pemerintah mengusulkan Anda cari mentor yang bisa bantu jaga konsistensi.",
    "Anda direkomendasikan rayakan progress kecil, jangan cuma fokus ke hasil akhir.",
    "Negara menyarankan Anda evaluasi rutin tiap minggu biar gak kehilangan arah.",
    "Anda berhak menerima dukungan dari grup 'Ambis yang Masih Belajar Bertahan'.",
    "Pemerintah mengusulkan Anda coba lagi dengan target yang lebih kecil dan jelas.",
  ],
  "Golongan Stabil Kalem": [
    "Anda direkomendasikan jadi mentor 'Cara Tenang Tapi Tetap Produktif'.",
    "Negara menyarankan ketenangan Anda dijadikan studi kasus manajemen stres.",
    "Anda berhak menerima sertifikat 'Paling Reliable Tanpa Banyak Drama'.",
    "Pemerintah mengusulkan Anda jadi pembicara soal kestabilan emosi.",
    "Anda direkomendasikan bagikan cara menjaga ketenangan ke yang gampang panik.",
    "Negara menyarankan Anda jadi role model 'Kalem di Luar, Solid di Dalam'.",
    "Anda layak dapat penghargaan 'Warga Paling Terkendali Sepanjang Tahun'.",
    "Pemerintah mengusulkan Anda jadi konsultan gaya hidup seimbang gratis.",
    "Anda direkomendasikan tetap pertahankan kestabilan ini sebagai kekuatan utama.",
    "Negara menyarankan Anda diundang jadi narasumber soal kontrol diri.",
    "Anda berhak menerima sertifikat 'Master Ketenangan Tanpa Banyak Bicara'.",
    "Pemerintah mengusulkan filosofi hidup Anda diajarkan di kelas motivasi.",
    "Anda direkomendasikan jadi inspirasi buat yang gampang emosi berlebihan.",
    "Negara menyarankan Anda dapat apresiasi karena selalu terkontrol di situasi sulit.",
    "Anda layak dapat gelar 'Paling Konsisten Tanpa Perlu Bukti Berlebihan'.",
    "Pemerintah mengusulkan Anda jadi duta kampanye 'Kalem Tapi Tetap Jalan'.",
    "Anda direkomendasikan tetap jaga keseimbangan ini sebagai identitas utama.",
    "Negara menyarankan Anda bagikan rahasia kestabilan ke warga yang gampang stres.",
    "Anda berhak menerima penghargaan dari Kementerian Ketenangan Nasional.",
    "Pemerintah mengusulkan Anda jadi panutan generasi yang gampang baper.",
  ],
  "Golongan Produktif Kepo": [
    "Anda direkomendasikan jadi jurnalis dadakan untuk berita lingkungan sekitar.",
    "Negara menyarankan rasa kepo Anda disalurkan jadi konten edukatif.",
    "Anda berhak menerima sertifikat 'Multitasking Kerja dan Update Timeline'.",
    "Pemerintah mengusulkan Anda jadi admin grup info RT karena selalu update.",
    "Anda direkomendasikan bagikan skill multitasking ke yang susah fokus.",
    "Negara menyarankan Anda jadi narasumber podcast 'Produktif Sambil Update'.",
    "Anda layak dapat penghargaan 'Paling Update Tanpa Mengganggu Produktivitas'.",
    "Pemerintah mengusulkan Anda jadi duta kampanye 'Kerja Jalan, Kepo Jalan'.",
    "Anda direkomendasikan jaga rasa penasaran ini, tapi tetap utamakan kerjaan.",
    "Negara menyarankan Anda jadi konsultan time management buat yang gampang FOMO.",
    "Anda berhak menerima sertifikat 'Ahli Bagi Waktu Kerja dan Kepo Sekaligus'.",
    "Pemerintah mengusulkan rasa kepo Anda diarahkan jadi riset pasar gratis.",
    "Anda direkomendasikan jadi moderator grup karena paling update info terbaru.",
    "Negara menyarankan Anda diundang jadi pembicara soal produktivitas modern.",
    "Anda layak dapat apresiasi karena bisa kerja serius tanpa ketinggalan info.",
    "Pemerintah mengusulkan Anda jadi panutan multitasking generasi sekarang.",
    "Anda direkomendasikan tetap jaga balance antara fokus kerja dan update sosial.",
    "Negara menyarankan Anda jadi mentor buat yang susah bagi waktu.",
    "Anda berhak menerima penghargaan dari Kementerian Produktivitas Modern.",
    "Pemerintah mengusulkan Anda jadi contoh: kerja jalan, kepo juga gak ketinggalan.",
  ],
  "Golongan Hustler Receh": [
    "Anda berhak menerima sertifikat 'Paling Gigih Walau Cuan Masih Receh'.",
    "Negara merekomendasikan Anda jadi mentor side hustle untuk pemula.",
    "Pemerintah mengusulkan Anda jadi pembicara seminar 'Mulai dari Kecil Itu Sah'.",
    "Anda direkomendasikan tetap konsisten, cuan besar cuma soal waktu.",
    "Negara menyarankan usaha kecil Anda didukung lewat program UMKM daerah.",
    "Anda berhak dapat penghargaan 'Paling Sabar Nunggu Hasil Usaha Membesar'.",
    "Pemerintah mengusulkan Anda jadi contoh: usaha kecil tapi gak pernah nyerah.",
    "Anda direkomendasikan bagikan semangat hustle ke yang gampang menyerah.",
    "Negara menyarankan Anda diundang jadi narasumber 'Dari Receh ke Berkah'.",
    "Anda layak dapat sertifikat 'Konsisten Usaha Walau Hasilnya Bertahap'.",
    "Pemerintah mengusulkan Anda jadi duta kampanye 'Usaha Kecil, Niat Besar'.",
    "Anda direkomendasikan tetap manfaatkan setiap peluang yang ada sekarang.",
    "Negara menyarankan Anda dapat apresiasi karena gak gampang nyerah usaha.",
    "Anda berhak menerima medali 'Paling Telaten Bangun Usaha dari Nol'.",
    "Pemerintah mengusulkan Anda jadi panutan generasi pengusaha pemula.",
    "Anda direkomendasikan tetap sabar, proses kecil ini bakal berbuah besar nanti.",
    "Negara menyarankan Anda diundang jadi pembicara workshop kewirausahaan.",
    "Anda berhak dapat penghargaan dari Kementerian Pengusaha Receh Berdaya.",
    "Pemerintah mengusulkan usaha Anda jadi studi kasus ketekunan nasional.",
    "Anda direkomendasikan tetap konsisten, cuan besar tinggal soal waktu aja.",
  ],
  "Golongan Mendekati Sultan": [
    "Anda direkomendasikan ikut seminar 'Finishing Touch Menuju Kemapanan'.",
    "Negara menyarankan Anda pertahankan momentum ini sampai benar-benar mapan.",
    "Anda berhak menerima sertifikat 'Hampir Sampai, Tinggal Sedikit Lagi'.",
    "Pemerintah mengusulkan Anda jadi contoh progress finansial yang konsisten.",
    "Anda direkomendasikan tetap disiplin, garis finish udah kelihatan jelas.",
    "Negara menyarankan Anda jadi mentor buat yang baru mulai usaha.",
    "Anda layak dapat penghargaan 'Paling Konsisten Mendekati Target Besar'.",
    "Pemerintah mengusulkan Anda jadi narasumber soal perjalanan menuju mapan.",
    "Anda direkomendasikan tetap jaga ritme ini, hasil maksimal tinggal soal waktu.",
    "Negara menyarankan Anda diundang jadi pembicara soal transisi finansial.",
    "Anda berhak menerima sertifikat 'Sultan Sedang dalam Proses Pematangan'.",
    "Pemerintah mengusulkan Anda jadi inspirasi buat yang baru mulai usaha.",
    "Anda direkomendasikan tetap fokus, target besar udah di depan mata.",
    "Negara menyarankan Anda jadi panutan soal kerja keras yang berbuah hasil.",
    "Anda layak dapat apresiasi karena progress Anda konsisten dan terlihat jelas.",
    "Pemerintah mengusulkan Anda jadi contoh kasus sukses transisi finansial.",
    "Anda direkomendasikan tetap jaga kedisiplinan ini sampai benar-benar tercapai.",
    "Negara menyarankan Anda diundang jadi mentor finansial untuk yang baru mulai.",
    "Anda berhak menerima penghargaan dari Kementerian Progress Finansial Warga.",
    "Pemerintah mengusulkan Anda lanjut konsisten, sultan tinggal soal waktu aja.",
  ],
  "Golongan Cuan Mengalir": [
    "Anda direkomendasikan jadi mentor diversifikasi income untuk pemula.",
    "Negara menyarankan strategi cuan Anda dijadikan studi kasus finansial.",
    "Anda berhak menerima sertifikat 'Ahli Bikin Uang Mengalir dari Banyak Arah'.",
    "Pemerintah mengusulkan Anda jadi pembicara seminar multiple income stream.",
    "Anda direkomendasikan bagikan strategi cuan ke yang masih single income.",
    "Negara menyarankan Anda jadi narasumber podcast soal financial freedom.",
    "Anda layak dapat penghargaan 'Paling Jago Kelola Sumber Cuan Beragam'.",
    "Pemerintah mengusulkan Anda jadi duta kampanye 'Diversifikasi Itu Penting'.",
    "Anda direkomendasikan tetap pertahankan sistem yang udah berjalan baik ini.",
    "Negara menyarankan Anda diundang jadi mentor finansial komunitas.",
    "Anda berhak menerima sertifikat 'Master Strategi Multiple Income Stream'.",
    "Pemerintah mengusulkan Anda jadi contoh sukses kelola banyak sumber rezeki.",
    "Anda direkomendasikan tetap waspada, jangan sampai kelola berlebihan jadi ribet.",
    "Negara menyarankan Anda jadi panutan soal financial planning yang matang.",
    "Anda layak dapat apresiasi karena rezeki Anda terkelola dengan rapi.",
    "Pemerintah mengusulkan Anda jadi inspirasi nasional soal kestabilan finansial.",
    "Anda direkomendasikan tetap syukuri dan kelola dengan bijak ke depannya.",
    "Negara menyarankan Anda diundang jadi pembicara workshop literasi finansial.",
    "Anda berhak menerima penghargaan dari Kementerian Diversifikasi Pendapatan.",
    "Pemerintah mengusulkan strategi Anda jadi bahan ajar finansial nasional.",
  ],
  "Golongan OKB Beneran": [
    "Anda direkomendasikan jadi mentor 'Naik Kelas Lewat Kerja Keras Asli'.",
    "Negara menyarankan kisah sukses Anda dijadikan bahan motivasi nasional.",
    "Anda berhak menerima sertifikat 'OKB Terverifikasi, Bukan Settingan'.",
    "Pemerintah mengusulkan Anda jadi pembicara seminar 'Naik Kelas Tanpa Tipu-Tipu'.",
    "Anda direkomendasikan bagikan kisah perjuangan ke generasi yang baru mulai.",
    "Negara menyarankan Anda jadi narasumber podcast soal kesuksesan nyata.",
    "Anda layak dapat penghargaan 'Bukti Hidup Kerja Keras Berbuah Manis'.",
    "Pemerintah mengusulkan Anda jadi duta kampanye 'Sukses Itu Proses, Bukan Settingan'.",
    "Anda direkomendasikan tetap pertahankan integritas di balik kesuksesan ini.",
    "Negara menyarankan Anda diundang jadi mentor untuk pengusaha pemula.",
    "Anda berhak menerima sertifikat 'Master Kelas Naik Status Finansial Asli'.",
    "Pemerintah mengusulkan Anda jadi contoh sukses yang bisa dipertanggungjawabkan.",
    "Anda direkomendasikan tetap rendah hati walau udah naik level finansial.",
    "Negara menyarankan Anda jadi panutan soal kesuksesan yang jujur dan nyata.",
    "Anda layak dapat apresiasi karena pencapaian Anda berdasarkan kerja keras.",
    "Pemerintah mengusulkan Anda jadi inspirasi nasional soal naik kelas dengan halal.",
    "Anda direkomendasikan tetap syukuri dan bagikan ilmu ke yang membutuhkan.",
    "Negara menyarankan Anda diundang jadi pembicara workshop kesuksesan otentik.",
    "Anda berhak menerima penghargaan dari Kementerian Kesuksesan Berbasis Usaha.",
    "Pemerintah mengusulkan kisah Anda jadi bahan ajar motivasi nasional.",
  ],
  "Golongan Sultan Tanpa Beban": [
    "Anda direkomendasikan jadi konsultan ketenangan finansial untuk warga lain.",
    "Negara menyarankan ketenangan Anda dijadikan standar hidup ideal nasional.",
    "Anda berhak menerima sertifikat 'Paling Tenang Karena Finansial Udah Aman'.",
    "Pemerintah mengusulkan Anda jadi pembicara soal financial freedom sejati.",
    "Anda direkomendasikan bagikan ketenangan ini ke yang masih struggling.",
    "Negara menyarankan Anda jadi narasumber podcast soal hidup tanpa beban uang.",
    "Anda layak dapat penghargaan 'Warga Paling Santuy Karena Udah Settle'.",
    "Pemerintah mengusulkan Anda jadi duta kampanye 'Aman Finansial, Tenang Hati'.",
    "Anda direkomendasikan tetap syukuri dan jaga kestabilan yang udah dicapai ini.",
    "Negara menyarankan Anda diundang jadi mentor financial freedom komunitas.",
    "Anda berhak menerima sertifikat 'Master Kelas Hidup Tanpa Beban Finansial'.",
    "Pemerintah mengusulkan Anda jadi contoh hidup tenang berkat kerja keras lalu.",
    "Anda direkomendasikan tetap rendah hati walau hidup udah serba nyaman.",
    "Negara menyarankan Anda jadi panutan soal ketenangan yang didapat dengan usaha.",
    "Anda layak dapat apresiasi karena bisa hidup tenang tanpa drama finansial.",
    "Pemerintah mengusulkan Anda jadi inspirasi nasional soal hidup yang aman dan stabil.",
    "Anda direkomendasikan tetap bagikan ilmu ke yang masih mengejar ketenangan ini.",
    "Negara menyarankan Anda diundang jadi pembicara workshop kebebasan finansial.",
    "Anda berhak menerima penghargaan dari Kementerian Ketenangan Finansial Warga.",
    "Pemerintah mengusulkan gaya hidup Anda jadi acuan hidup ideal nasional.",
  ],
  "Golongan Bertahan Hidup Doang": [
    "Anda direkomendasikan ikut program bantuan dasar dari Kementerian Survival.",
    "Negara menyarankan Anda diberi apresiasi karena tetap kuat di kondisi terbatas.",
    "Anda berhak menerima sertifikat 'Paling Tangguh Hadapi Keterbatasan Harian'.",
    "Pemerintah mengusulkan Anda dapat dukungan moral dari sesama pejuang survival.",
    "Anda direkomendasikan ikut pelatihan dasar literasi keuangan untuk pemula.",
    "Negara menyarankan Anda dapat akses informasi soal bantuan sosial yang ada.",
    "Anda layak dapat penghargaan 'Paling Kuat Bertahan di Kondisi Apapun'.",
    "Pemerintah mengusulkan Anda ikut program pelatihan kerja biar ada tambahan skill.",
    "Anda direkomendasikan tetap semangat, kondisi ini bukan kondisi selamanya.",
    "Negara menyarankan Anda gabung komunitas saling bantu sesama yang struggling.",
    "Anda berhak menerima dukungan dari Kementerian Ketahanan Hidup Warga.",
    "Pemerintah mengusulkan Anda ikut program literasi finansial dasar gratis.",
    "Anda direkomendasikan catat pengeluaran harian biar lebih terkontrol.",
    "Negara menyarankan Anda jangan ragu cari bantuan kalau memang dibutuhkan.",
    "Anda layak dapat apresiasi karena tetap berjuang walau kondisi terbatas.",
    "Pemerintah mengusulkan Anda ikut pelatihan keterampilan biar peluang kerja luas.",
    "Anda direkomendasikan tetap kuat, semua kondisi sulit ada masanya berakhir.",
    "Negara menyarankan Anda dapat dukungan psikologis biar mental tetap kuat.",
    "Anda berhak menerima penghargaan 'Pejuang Survival Paling Gigih Tahun Ini'.",
    "Pemerintah mengusulkan Anda tetap semangat, satu langkah kecil tetap progress.",
  ],
  "Golongan Ngarep Tapi Santai": [
    "Anda direkomendasikan jadi mentor 'Cara Berharap Tanpa Bikin Stres'.",
    "Negara menyarankan filosofi harapan Anda dijadikan kelas motivasi ringan.",
    "Anda berhak menerima sertifikat 'Optimis Tapi Tetap Realistis dan Tenang'.",
    "Pemerintah mengusulkan Anda jadi pembicara soal harapan tanpa kecemasan.",
    "Anda direkomendasikan bagikan cara pandang ini ke yang gampang cemas.",
    "Negara menyarankan Anda jadi role model 'Berharap Boleh, Ngoyo Nggak Perlu'.",
    "Anda layak dapat penghargaan 'Paling Santai Menjalani Proses Menuju Harapan'.",
    "Pemerintah mengusulkan Anda jadi konsultan ketenangan untuk yang gampang khawatir.",
    "Anda direkomendasikan tetap pertahankan keseimbangan harapan dan ketenangan ini.",
    "Negara menyarankan Anda diundang jadi narasumber soal optimisme yang sehat.",
    "Anda berhak menerima sertifikat 'Master Kelas Harapan Tanpa Drama Berlebihan'.",
    "Pemerintah mengusulkan filosofi hidup Anda diajarkan ke yang mudah panik.",
    "Anda direkomendasikan jadi inspirasi buat yang terlalu maksa hasil instan.",
    "Negara menyarankan Anda dapat apresiasi karena tetap tenang sambil berharap.",
    "Anda layak dapat gelar 'Paling Jago Berharap Tanpa Kehilangan Kewarasan'.",
    "Pemerintah mengusulkan Anda jadi duta kampanye 'Sabar Itu Strategi Juga'.",
    "Anda direkomendasikan tetap jaga cara pandang ini sebagai kekuatan utama.",
    "Negara menyarankan Anda bagikan ketenangan ini ke warga yang gampang cemas.",
    "Anda berhak menerima penghargaan dari Kementerian Harapan yang Sehat.",
    "Pemerintah mengusulkan Anda jadi panutan generasi yang gampang overthinking.",
  ],
  "Golongan Capek Tapi Lanjut": [
    "Anda direkomendasikan ikut program istirahat wajib, minimal sehari penuh.",
    "Negara menyarankan Anda dapat apresiasi karena gak pernah benar-benar berhenti.",
    "Anda berhak menerima sertifikat 'Paling Gigih Walau Energi Udah Menipis'.",
    "Pemerintah mengusulkan Anda diberi akses gratis ke layanan kesehatan mental.",
    "Anda direkomendasikan luangkan waktu istirahat biar gak burnout berkepanjangan.",
    "Negara menyarankan Anda jadi contoh ketahanan mental warga yang luar biasa.",
    "Anda layak dapat penghargaan 'Paling Kuat Bertahan di Tengah Kelelahan'.",
    "Pemerintah mengusulkan Anda dapat hak cuti tambahan dari Kementerian Kelelahan.",
    "Anda direkomendasikan jangan ragu minta bantuan kalau memang udah berat.",
    "Negara menyarankan Anda gabung support group sesama pejuang yang lelah.",
    "Anda berhak menerima dukungan dari Kementerian Ketahanan Mental Warga.",
    "Pemerintah mengusulkan Anda ikut program self-care wajib seminggu sekali.",
    "Anda direkomendasikan evaluasi: apakah perlu kurangi beban sedikit demi sedikit.",
    "Negara menyarankan Anda dapat apresiasi karena tanggung jawab Anda tinggi.",
    "Anda layak dapat sertifikat 'Tangguh Tapi Tetap Manusia, Boleh Capek'.",
    "Pemerintah mengusulkan Anda diberi waktu rehat sebelum lanjut lagi.",
    "Anda direkomendasikan tetap jaga kesehatan, capek itu sinyal bukan kelemahan.",
    "Negara menyarankan Anda jangan paksa diri kalau memang butuh berhenti sebentar.",
    "Anda berhak menerima penghargaan 'Pejuang Paling Konsisten Walau Lelah'.",
    "Pemerintah mengusulkan Anda istirahat dulu, baru lanjut lagi besok.",
  ],
  "Golongan Tukang PHP Diri Sendiri": [
    "Anda direkomendasikan ikut terapi 'Menepati Janji ke Diri Sendiri, Vol. 1'.",
    "Negara menyarankan Anda evaluasi pola: kenapa janji sendiri sering diingkari.",
    "Anda berhak menerima sertifikat 'Paling Jago Kasih Harapan ke Diri Sendiri'.",
    "Pemerintah mengusulkan Anda buat target yang lebih kecil dan realistis.",
    "Anda direkomendasikan tulis janji di tempat yang sering keliatan tiap hari.",
    "Negara menyarankan Anda cari teman yang bisa nagih komitmen Anda.",
    "Anda layak dapat dukungan dari Kementerian Konsistensi Diri Sendiri.",
    "Pemerintah mengusulkan Anda ikut tantangan 7 hari tepati janji kecil.",
    "Anda direkomendasikan jujur ke diri sendiri soal alasan sering menunda.",
    "Negara menyarankan Anda buat reward kecil tiap berhasil tepati janji.",
    "Anda berhak menerima sertifikat 'Spesialis Negosiasi Ulang dengan Diri Sendiri'.",
    "Pemerintah mengusulkan Anda evaluasi: ini soal waktu atau soal motivasi.",
    "Anda direkomendasikan mulai dari komitmen kecil yang gampang dijalani.",
    "Negara menyarankan Anda jangan terlalu keras saat gagal nepatin janji.",
    "Anda layak dapat apresiasi karena masih mau coba lagi walau sering gagal.",
    "Pemerintah mengusulkan Anda buat sistem pengingat yang lebih konsisten.",
    "Anda direkomendasikan rayakan progress kecil, jangan cuma fokus ke kegagalan.",
    "Negara menyarankan Anda coba metode baru kalau cara lama gak berhasil.",
    "Anda berhak menerima dukungan dari grup 'Sama-Sama Belajar Konsisten'.",
    "Pemerintah mengusulkan Anda mulai lagi hari ini, dengan target yang lebih jujur.",
  ],
  "Golongan Mendadak Bijak": [
    "Anda direkomendasikan jadi konselor part-time untuk teman yang lagi galau.",
    "Negara menyarankan kata-kata bijak Anda dikumpulkan jadi buku motivasi.",
    "Anda berhak menerima sertifikat 'Ahli Kasih Nasihat, Belajar Jalanin Sendiri'.",
    "Pemerintah mengusulkan Anda jadi pembicara podcast walau hidup masih proses.",
    "Anda direkomendasikan terapkan nasihat sendiri ke kehidupan pribadi juga.",
    "Negara menyarankan Anda jadi mentor dadakan untuk yang lagi butuh insight.",
    "Anda layak dapat penghargaan 'Paling Bijak di Saat yang Gak Terduga'.",
    "Pemerintah mengusulkan Anda jadi narasumber 'Teori Kuat, Praktik Belajar'.",
    "Anda direkomendasikan tulis insight Anda biar gak cuma jadi obrolan lewat.",
    "Negara menyarankan Anda jadi contoh: bijak ke orang, belajar bijak ke diri sendiri.",
    "Anda berhak menerima sertifikat 'Quote Generator Alami Tanpa Sertifikasi'.",
    "Pemerintah mengusulkan Anda jadi pembicara seminar 'Hidup yang Masih Belajar'.",
    "Anda direkomendasikan praktikkan dulu nasihat sendiri sebelum kasih ke orang.",
    "Negara menyarankan Anda jadi panutan soal refleksi diri yang jujur.",
    "Anda layak dapat apresiasi karena insight Anda sering bantu orang lain.",
    "Pemerintah mengusulkan Anda jadi mentor curhat resmi di lingkungan sekitar.",
    "Anda direkomendasikan tetap berbagi insight, tapi jangan lupa urus diri sendiri.",
    "Negara menyarankan Anda jadi inspirasi: bijak bukan berarti hidup sempurna.",
    "Anda berhak menerima penghargaan dari Kementerian Insight Dadakan Nasional.",
    "Pemerintah mengusulkan Anda lanjut berbagi, sambil pelan-pelan berbenah diri.",
  ],
  "Golongan Modal Nekat": [
    "Anda direkomendasikan ikut kelas manajemen risiko biar nekatnya lebih terarah.",
    "Negara menyarankan keberanian Anda dijadikan studi kasus pengambilan keputusan.",
    "Anda berhak menerima sertifikat 'Paling Berani Coba Duluan, Mikir Belakangan'.",
    "Pemerintah mengusulkan Anda jadi pembicara soal keberanian mengambil risiko.",
    "Anda direkomendasikan tetap nekat, tapi mulai siapkan plan B juga.",
    "Negara menyarankan Anda jadi mentor untuk yang takut mulai sesuatu.",
    "Anda layak dapat penghargaan 'Paling Jago Lompat Duluan, Cari Jaring Belakangan'.",
    "Pemerintah mengusulkan Anda jadi narasumber soal keberanian dalam berusaha.",
    "Anda direkomendasikan evaluasi hasil nekat Anda, biar makin terarah ke depan.",
    "Negara menyarankan Anda jadi contoh: keberanian lebih penting dari kesempurnaan.",
    "Anda berhak menerima sertifikat 'Master Kelas Keberanian Tanpa Banyak Mikir'.",
    "Pemerintah mengusulkan Anda jadi inspirasi buat yang terlalu banyak ragu.",
    "Anda direkomendasikan tetap nekat, tapi sisihkan dana darurat juga.",
    "Negara menyarankan Anda jadi panutan soal aksi nyata tanpa banyak alasan.",
    "Anda layak dapat apresiasi karena berani ambil langkah walau belum sempurna.",
    "Pemerintah mengusulkan Anda jadi mentor 'Coba Dulu, Belajar Sambil Jalan'.",
    "Anda direkomendasikan tetap pertahankan keberanian ini sebagai kekuatan utama.",
    "Negara menyarankan Anda bagikan keberanian ini ke yang gampang ragu-ragu.",
    "Anda berhak menerima penghargaan dari Kementerian Keberanian Mengambil Risiko.",
    "Pemerintah mengusulkan Anda jadi panutan generasi yang takut gagal.",
  ],
  "Golongan Pejuang Tanggal Tua": [
    "Anda direkomendasikan ikut workshop 'Strategi Bertahan di Minggu Terakhir'.",
    "Negara menyarankan jurus survival Anda dijadikan modul literasi keuangan.",
    "Anda berhak menerima sertifikat 'Veteran Tangguh Hadapi Tanggal Tua'.",
    "Pemerintah mengusulkan Anda jadi mentor untuk yang baru kerja dan belum siap.",
    "Anda direkomendasikan bagikan tips bertahan ke yang sering boncos juga.",
    "Negara menyarankan Anda jadi narasumber 'Cara Kreatif Makan di Akhir Bulan'.",
    "Anda layak dapat penghargaan 'Paling Jago Stretching Budget Sampai Gajian'.",
    "Pemerintah mengusulkan Anda jadi duta kampanye 'Atur Uang dari Awal Bulan'.",
    "Anda direkomendasikan evaluasi pengeluaran biar tanggal tua makin ringan.",
    "Negara menyarankan Anda gabung komunitas yang sama-sama berjuang tiap bulan.",
    "Anda berhak menerima sertifikat 'Master Strategi Survival Akhir Bulan'.",
    "Pemerintah mengusulkan Anda jadi contoh ketahanan finansial yang konsisten.",
    "Anda direkomendasikan coba sisihkan sedikit di awal biar akhir gak terlalu berat.",
    "Negara menyarankan Anda jadi panutan soal kreativitas bertahan hidup.",
    "Anda layak dapat apresiasi karena selalu berhasil lewati fase sulit tiap bulan.",
    "Pemerintah mengusulkan Anda jadi mentor literasi keuangan untuk pemula.",
    "Anda direkomendasikan tetap semangat, gajian selalu datang pada waktunya.",
    "Negara menyarankan Anda bagikan jurus bertahan ke yang baru mulai kerja.",
    "Anda berhak menerima penghargaan 'Pejuang Tanggal Tua Paling Konsisten'.",
    "Pemerintah mengusulkan Anda jadi inspirasi soal ketahanan finansial bulanan.",
  ],
  "Golongan Anti Mainstream": [
    "Anda direkomendasikan jadi pembicara soal keberanian jadi diri sendiri.",
    "Negara menyarankan pilihan hidup Anda dijadikan studi kasus keberagaman.",
    "Anda berhak menerima sertifikat 'Paling Berani Beda dari Kebanyakan Orang'.",
    "Pemerintah mengusulkan Anda jadi mentor untuk yang takut tampil beda.",
    "Anda direkomendasikan tetap percaya diri dengan jalan yang Anda pilih sendiri.",
    "Negara menyarankan Anda jadi narasumber podcast soal jalan hidup alternatif.",
    "Anda layak dapat penghargaan 'Paling Otentik Tanpa Ikut Arus Mayoritas'.",
    "Pemerintah mengusulkan Anda jadi duta kampanye 'Beda Itu Bukan Salah'.",
    "Anda direkomendasikan bagikan keberanian ini ke yang takut dianggap aneh.",
    "Negara menyarankan Anda jadi contoh keberanian mengambil jalan yang berbeda.",
    "Anda berhak menerima sertifikat 'Master Kelas Jadi Diri Sendiri Tanpa Ragu'.",
    "Pemerintah mengusulkan Anda jadi inspirasi buat yang terlalu takut dinilai orang.",
    "Anda direkomendasikan tetap jaga keunikan ini sebagai kekuatan utama Anda.",
    "Negara menyarankan Anda jadi panutan soal keberanian mengambil keputusan sendiri.",
    "Anda layak dapat apresiasi karena berani jalan beda walau sering dipertanyakan.",
    "Pemerintah mengusulkan Anda jadi mentor 'Hidup Sesuai Diri, Bukan Sesuai Tren'.",
    "Anda direkomendasikan tetap percaya proses yang Anda jalani sendiri ini.",
    "Negara menyarankan Anda bagikan cerita ini ke yang masih ragu jadi beda.",
    "Anda berhak menerima penghargaan dari Kementerian Keberagaman Jalan Hidup.",
    "Pemerintah mengusulkan Anda jadi panutan generasi yang takut keluar dari standar.",
  ],
  "Golongan Investor Receh": [
    "Anda direkomendasikan jadi mentor investasi untuk pemula dengan modal kecil.",
    "Negara menyarankan kebiasaan investasi Anda dijadikan kurikulum sekolah.",
    "Anda berhak menerima sertifikat 'Konsisten Investasi Walau Modal Receh'.",
    "Pemerintah mengusulkan Anda jadi pembicara seminar 'Mulai Investasi dari Nol'.",
    "Anda direkomendasikan bagikan ilmu compound interest ke yang masih ragu mulai.",
    "Negara menyarankan Anda jadi narasumber podcast literasi finansial dasar.",
    "Anda layak dapat penghargaan 'Paling Disiplin Sisihkan Uang untuk Masa Depan'.",
    "Pemerintah mengusulkan Anda jadi duta kampanye 'Investasi Gak Perlu Modal Besar'.",
    "Anda direkomendasikan tetap konsisten, hasil compound bakal terasa nanti.",
    "Negara menyarankan Anda jadi mentor untuk yang takut mulai investasi.",
    "Anda berhak menerima sertifikat 'Master Kelas Investasi dari Modal Kecil'.",
    "Pemerintah mengusulkan Anda jadi contoh sukses kebiasaan finansial yang baik.",
    "Anda direkomendasikan tetap belajar instrumen baru biar makin paham risiko.",
    "Negara menyarankan Anda jadi panutan soal kesabaran dalam berinvestasi.",
    "Anda layak dapat apresiasi karena disiplin sisihkan uang walau nominal kecil.",
    "Pemerintah mengusulkan Anda jadi inspirasi nasional soal investasi jangka panjang.",
    "Anda direkomendasikan tetap konsisten, proses kecil ini bakal jadi besar nanti.",
    "Negara menyarankan Anda diundang jadi pembicara workshop investasi pemula.",
    "Anda berhak menerima penghargaan dari Kementerian Literasi Investasi Warga.",
    "Pemerintah mengusulkan kebiasaan Anda jadi bahan ajar finansial nasional.",
  ],
  "Golongan Crazy Rich Receh": [
    "Anda direkomendasikan segera membuka cabang usaha kedua, walau cabang pertama masih nyicil.",
    "Negara menyarankan Anda evaluasi: gaya hidup atau tabungan yang harus dinaikkan dulu.",
    "Anda berhak menerima sertifikat 'Paling Jago Tampil Mewah Walau Strategi Ketat'.",
    "Pemerintah mengusulkan Anda jadi konsultan personal branding untuk yang baru mulai usaha.",
    "Anda direkomendasikan tetap jaga image, tapi jangan lupa nabung juga.",
    "Negara menyarankan Anda jadi narasumber 'Cara Kelihatan Settle Walau Masih Usaha'.",
    "Anda layak dapat penghargaan 'Paling Konsisten Jaga Gaya Tanpa Bocor Keuangan'.",
    "Pemerintah mengusulkan Anda jadi duta kampanye 'Flexing Boleh, Asal Terencana'.",
    "Anda direkomendasikan evaluasi pengeluaran lifestyle biar makin balance.",
    "Negara menyarankan Anda jadi contoh: image kuat, perencanaan juga harus kuat.",
    "Anda berhak menerima sertifikat 'Master Kelas Jaga Citra Sambil Atur Strategi'.",
    "Pemerintah mengusulkan Anda jadi mentor personal finance untuk yang doyan flexing.",
    "Anda direkomendasikan tetap pertahankan gaya hidup ini, tapi imbangi dengan tabungan.",
    "Negara menyarankan Anda jadi panutan soal gaya hidup tinggi yang tetap terencana.",
    "Anda layak dapat apresiasi karena bisa balance antara penampilan dan kemampuan.",
    "Pemerintah mengusulkan Anda jadi inspirasi nasional soal personal branding cerdas.",
    "Anda direkomendasikan tetap konsisten, sultan beneran tinggal soal waktu aja.",
    "Negara menyarankan Anda diundang jadi pembicara soal gaya hidup dan strategi finansial.",
    "Anda berhak menerima penghargaan dari Kementerian Personal Branding Cerdas.",
    "Pemerintah mengusulkan gaya hidup Anda jadi studi kasus branding yang terencana.",
  ],
};

export function pilihRekomendasiAcak(namaGolongan) {
  const list = REKOMENDASI[namaGolongan];
  if (!list || list.length === 0) return "";
  const idx = Math.floor(Math.random() * list.length);
  return list[idx];
}
